version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large

    steps:
      - run:
          name: Set and retrieve vars
          command: |
            echo $TEST1
            # echo $TEST2
            export $TEST1=CHANGED
            # setenv $TEST2=CHANGED
            echo $TEST1
            # echo $TEST2
      - run:
          name: Retreive var
          command: echo $TEST1
            
      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test
