# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build:

jobs:
  checkout_and_build:
    docker:
      - image: cimg/ruby:2.7.2-browsers
    steps:
      - run:
          name: Install ImageMagick
          command: |
            sudo apt-get install -y aptitude
            sudo aptitude -y install imagemagick
            sudo aptitude -y install libmagickcore-dev
            sudo aptitude -y install libmagickwand-dev