version: 2.1

check-should-build-for-prod: &check-should-build-for-prod 
  equal: [ false, equal: [ master, << pipeline.git.branch >> ]]

jobs: 
  build:
    docker:
      - image: cimg/base:current
        # auth:
        #   username: $DOCKERHUB_USER
        #   password: $DOCKERHUB_PASS
    resource_class: small
    steps:
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: Main
                command: echo "This is on main"
                # background: true
      - when:
          condition:
            not: *check-should-build-for-prod
          steps:
            - run:
                name: Not Main
                command: echo "This is not on main"
      # - snyk/install

  # test:
  #   docker:
  #     - image: cimg/base:current
  #   resource_class: small
  #   steps:
  #     - run: pwd
          
workflows:
  build_and_deploy_api:
    # when:
    #   equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - build
      #     context:
      #       - dockerhub
      # - test
  # build_and_deploy_webhook:
  #   when:
  #     equal: [ webhook, << pipeline.trigger_source >> ]
  #   jobs:
  #     - build:
  #         context:
  #           - dockerhub
  #     - test