# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build:
          context:
            - my-context

jobs:
  checkout_and_build:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - run:
          name: context
          command: echo $demokey
#      - run:
#          name: Update apt
#          command: sudo apt update      
      - run:
          name: Install mysql client
          command: sudo apt install -y --fix-missing default-mysql-client
      - run:
          name: Get directory location and echo command
          command: |
            echo pwd
            pwd