version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large
    working_directory: ~/stuff

    steps:
      - run:
          name: Currect dir
          command: |
            ls -al
            pwd

      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test
