version: 2.1
orbs:
  go: circleci/go@1.7.0
jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202010-01
    environment:
      XXX: stuff
    steps:
      - run:
          name: Current dir
          command: pwd

workflows:
  build:
    jobs:
      - build