version: 2.1

orbs:
  # python: circleci/python@2.1.1
  # mac: circleci/macos@2.3.4

jobs:
  build:
    # parameters:
    #   xcode_version:
    #     type: string
    #     default: "14.3.1"
    #   device_version:
    #     type: string
    #     default: "iPhone 13 Pro Max"
    macos:
      xcode: "14.3.1"
    # resource_class: macos.x86.medium.gen2
    steps:
      - run: pwd
      
  # deploy:
  #   macos: 
  #     xcode: "13.4.1"
  #   resource_class: macos.x86.medium.gen2
  #   when:
  #     condition:
  #       equal: [true, true]
  #     steps:
  #       - run: pwd


workflows:
  workflow-mac:
    jobs:
      - build
          # matrix:
          #   parameters:
          #     xcode_version: ["13.4.1"]
          #     device_version: ["iPhone 14 Pro Max"]
          # post-steps:
          #   - run: pwd
      # - deploy