version: 2.1

orbs:
  # python: circleci/python@2.1.1
  mac: circleci/macos@2.3.4

jobs:
  build:
    parameters:
      xcode_version:
        type: string
        default: "13.4.1"
      device_version:
        type: string
        default: "iPhone 13 Pro Max"
    macos:
      xcode: << parameters.xcode_version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - run: xcrun simctl list
      - mac/preboot-simulator:
          version: '14.5'
          device: << parameters.device_version >>
      - run: xcrun simctl list
      # - run:
      #     command: xcrun simctl bootstatus "${MACOS_ORB_DEVICE_UDID}"
      - mac/wait-until-simulator-booted # doesnt work on m1
workflows:
  workflow-mac:
    jobs:
      - build:
          matrix:
            parameters:
              xcode_version: ["13.4.1"]
              device_version: ["iPhone 14 Pro Max"]
          post-steps:
            - run: pwd
            - mac/install-rosetta