version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

executors:
  newimage:
    aws-ecr/default:
      image: ubuntu-2004:202111-01

workflows:
  build-test:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ECR_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ECR_AWS_SECRET_ACCESS_KEY
          repo: al-test
          executor: newimage