version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: stable

      steps:
        - run:
            name: Install dotnet 4.8
            command: choco install netfx-4.8-devpack

        - run:
             name: Check dotnet versions
             command: dotnet --list-sdks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build