version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: stable

      steps:

        - run:
            name: Check dotnet versions
            command: dotnet --list-sdks

        - run:
            name: Install dotnet 4.8
            command: |
              # Run a separate PowerShell process because the script calls exit, so it will end the current PowerShell session.
              &powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 4.8.0xx -Quality signed"
            shell: powershell.exe

        - run:
             name: Check dotnet versions
             command: dotnet --list-sdks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build