version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Check top
          command: top
          background: true
      - run:
          name: Profile CPU and memory every 5s (background)
          command: |
            while true; do
              sleep 5
              printf "\n\n$(date)\n"
              top -b -c -n 1
              echo "======"
            done
          background: true
      - run:
          name: Sleep
          command: sleep 30


workflows:
  build_and_deploy:
    jobs:
      - build

# VS Code Extension Version: 1.2.0