version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: 
      name: win/server-2022
      size: xlarge
    # version: edge
    steps:

      - run:
          
          name: Installer Projects extension install
          command: | 
            #cd "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build"
            #./vcvarsall.bat x64   
            & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" /q /a --wait "$env:CIRCLE_WORKING_DIRECTORY\Tools\InstallerProjects.vsix"
            $pathtoVsixFile = "$env:CIRCLE_WORKING_DIRECTORY\Tools\InstallerProjects.vsix"
            $args = '/quiet "{0}InstallerProjects.vsix"' -f $pathtoVsixFile;
            $result = Start-Process -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VSIXInstaller.exe" -ArgumentList $args -Wait -PassThru     
            
          shell: powershell.exe

      - run:
          name: Pause for 2 minutes
          command: Start-Sleep -s 120
          shell: powershell.exe

      # - run:
          
      #     name: Soln build
      #     command: | 
      #       & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" "$env:CIRCLE_WORKING_DIRECTORY\Project\PathWandGUI\PathWandGUI.sln" /build Debug
      #       cd "$env:CIRCLE_WORKING_DIRECTORY\Project\PathWandGUI\$env:SOLN_CONFIG"
      #       dir
            
      #     shell: powershell.exe

workflows:
  version: 2
  build-deploy:
    jobs:
      - build