version: 2.1
  
jobs:
  build:
    machine: 
      image: ubuntu-2004:202111-02
    resource_class: medium
    
    steps:
      - checkout
      - store_test_results:
          path: bazel-testlogs

workflows:
  build-deploy:
    jobs:
      - build