version: 2.1

orbs:
  mac: circleci/macos@dev:20758105bf04a1fb756a623352dcfdca1c27ec81
  browser: circleci/browser-tools@1.2.5

jobs:
  build:
    macos:
      xcode: 13.4.0
      # resource_class: macos.x86.medium.gen2
    steps:
      - run:
          name: Check Docker version
          # command: curl --connect-timeout 20.0 --max-time 20.0 -Lo ./firebase_bin https://firebase.tools/bin/macos/latest
          command: docker --version
      - run:
          name: Update Docker
          command: sudo apt update && sudo apt --only-upgrade install docker
      # - mac/enable-vnc
      # - browser/install-chrome:
      #     chrome-version: latest
      
workflow:
  build:
    jobs:
      - build