version: 2.1

orbs:
  mac-permissions: circleci/macos@1.1.0

jobs:
  permissions-check:

    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - mac-permissions/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
          # Adds ScreenCapture permission to Terminal
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
