version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: stable

      steps:
        - checkout
        - run:
            name: Check Windows 10 SDK version
            command: |
              $WindowsSdkToolsPath = gci 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK' |
                select -Last 1 |
                gci | ? { $_.PSChildName -eq 'WinSDK-NetFx40Tools' } |
                Get-ItemPropertyValue -Name InstallationFolder
            shell: powershell.exe

        - run:
            name: Install new Windows 10 SDK version with choco
            command: choco install windows-sdk-10.0 --version 10.0.19041.0 --force
            shell: powershell.exe

        - run:
            command: |
              $WindowsSdkToolsPath = gci 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK' |
                select -Last 1 |
                gci | ? { $_.PSChildName -eq 'WinSDK-NetFx40Tools' } |
                Get-ItemPropertyValue -Name InstallationFolder
            shell: powershell.exe

workflows:
  version: 2
  build-deploy:
    jobs:
      - build