version: 2.1

jobs:
  build_and_test:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - run:
          name: Check Docker version
          command: docker --version

workflows:
  build:
    jobs:
      - build_and_test
