version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2-node
    resource_class: small

    steps:
      - run:
          name: Create script
          command: touch script.sh && echo "echo \"Hello world!\"" >> script.sh
          background: false
      - run:
          name: Set executable
          command: chmod 755 script.sh
      - run:
          name: Current dir
          command: ls -al
      - run:
          name: Run script
          command: ./script.sh

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build # << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3"]