{
  "version": 2.1,
  "parameters": {
    "tag": {
      "default": "3.8",
      "description": "The `cimg/python` Docker image version tag.",
      "type": "string"
    },
    "use-redis": {
      "default": true,
      "description": "Sidecar Redis container if required",
      "type": "boolean"
    }
  },
  "executors": {
    "base": {
      "docker": [
        {
          "image": "cimg/python:<< pipeline.parameters.tag >>"
        },
        {
          "image": "redis:latest"
        }
      ]
    }
  },
  "jobs": {
    "build": {
      "executor": "base",
      "steps": [
        {
          "run": "echo hello"
        }
      ]
    }
  }
}