version: 2.1

# orbs:
  # snyk: snyk/snyk@1.5.2



jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small

    parameters:
      number:
        type: string
        default: "1"

    # working_directory: /canton

    steps:
      - run:
          name: Install Snyk
          command: |
            if [[ ! -x "/tmp/snyk" ]]; then
              SNYK_CLI_VERSION=$(cat "/tmp/.snyk-version")
              echo "Downloading Snyk CLI version ${SNYK_CLI_VERSION}"
              curl -sO --retry 6 https://static.snyk.io/cli/v${SNYK_CLI_VERSION}/snyk-linux
              curl -sO --retry 6 https://static.snyk.io/cli/v${SNYK_CLI_VERSION}/snyk-linux.sha256
              sha256sum -c snyk-linux.sha256
              sudo mv snyk-linux /tmp/snyk
              sudo chmod +x /tmp/snyk
            fi
            sudo ln -sf /tmp/snyk /usr/local/bin/snyk

    # steps:
    #   - run:
    #       name: Set and retrieve vars
    #       command: |
    #         sudo mkdir /canton
    #         # echo 'export "CIRCLE_WORKING_DIRECTORY=/canton"' >> $BASH_ENV
    #         # echo 'export "CIRCLE_BUILD_NUM=123"' >> $BASH_ENV
    #         # source $BASH_ENV
    #         echo $CIRCLE_WORKING_DIRECTORY
            
    #   - run:
    #       name: Retreive var
    #       working_directory: /canton
    #       command: |
    #         echo $CIRCLE_WORKING_DIRECTORY
    #         pwd
            
      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              number: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]