version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    parameters:
      xcode_version:
        default: "14.3.1"
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - python/install-packages

workflows:
  workflow-mac:
    jobs:
      - build:
          matrix:
            parameters:
              xcode_version: ["14.2.0", "14.3.1"]