# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build

jobs:
  checkout_and_build:
    machine:
      - image: ubuntu-2004:202107-02
    steps:
      - run:
          name: prep
          command: |
            sudo apt update
            sudo apt autoremove