version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  nodestuffs:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: RVM Stuff
          command: |
            rvm use 2.7.2
            ruby -v
            rvm use 3.9.5
            ruby -v


workflows:
    welcome:
      jobs:
        nodestuffs:
        - welcome/run:
            filters:
              branches:
                ignore:
                  - testbranch
