version: 2.1

parameters:
  pipelineSingleQuotes:
    type: string
    default: '1234567890'
  pipelineDoubleQuotes:
    type: string
    default: "1234567890"

jobs:
  local:

    docker:
      - image: cimg/ruby:2.7.4

    parameters:
      elementSingleQuotes:
        type: string
        default: '1234567890'
      elementDoubleQuotes:
        type: string
        default: "1234567890"

    steps:
      - run:
          name: Pipeline Single Quotes!
          command: echo << pipeline.parameters.pipelineSingleQuotes >>
      - run:
          name: Pipeline Double Quotes!
          command: echo << pipeline.parameters.pipelineDoubleQuotes >>
      - run:
          name: Element Single Quotes!
          command: echo << parameters.elementSingleQuotes >>
      - run:
          name: Element Double Quotes!
          command: echo << parameters.elementDoubleQuotes >>
      - run:
          name: What is my password though?
          command: echo $FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
             
workflows:
  version: 2
  build:
    jobs:
      - local
