version: 2.1

orbs:
  windows: circleci/windows@5.0.0

# executors:
#   win-med:
#     machine:
#       image: 'windows-server-2019:current'
#     resource_class: 'windows.medium'
#   win-xl:
#     machine:
#       image: 'windows-server-2019:current'
#     resource_class: 'windows.xlarge'
#   win-gpu:
#     machine:
#       image: 'windows-server-2019-cuda:current'
#     resource_class: 'windows.gpu.nvidia.medium'
  # win-gui-2023-07:
  #   machine:
  #     image: 'windows-server-2022-gui:2023.06.1
  #   resource_class: 'windows.medium'
  # win-gui-2023-08:
  #   machine:
  #     image: 'windows-server-2022-gui:2023.06.1'
  #   resource_class: 'windows.medium'

jobs:

  gitclone-1:
    executor: 
      name: windows/server-2019
    # parameters:
    #   exec:
    #     type: executor
    # executor: << parameters.exec >>
    steps:
      # Start recording
      # - win-perf-diag/start-perflog
      # - win-perf-diag/record-wpr-in-background:
      #     for-sec: 100
      #     split-by-sec: 60
      - run:
          command: C:\Users\circleci.PACKER-648C8BAD\DiskSpd\amd64\diskspd.exe -d60 -W15 -C15 -c128M -t4 -o4 -b8k -L -r -Sh -w50 c:\disk-speed-test.dat
          name: Disk Speed
      # Stop recording and save records
      # - win-perf-diag/ensure-and-save-wpr
      # - win-perf-diag/stop-and-save-perflog

  gitclone-2:
    executor: 
      name: windows/server-2019-cuda
    # parameters:
    #   exec:
    #     type: executor
    # executor: << parameters.exec >>
    steps:
      # Start recording
      # - win-perf-diag/start-perflog
      # - win-perf-diag/record-wpr-in-background:
      #     for-sec: 100
      #     split-by-sec: 60
      - run:
          command: C:\Users\circleci.PACKER-648C8BAD\DiskSpd\amd64\diskspd.exe -d60 -W15 -C15 -c128M -t4 -o4 -b8k -L -r -Sh -w50 c:\disk-speed-test.dat
          name: Disk Speed
      # Stop recording and save records
      # - win-perf-diag/ensure-and-save-wpr
      # - win-perf-diag/stop-and-save-perflog

  gitclone-3:
    executor: 
      name: windows/server-2022
    # parameters:
    #   exec:
    #     type: executor
    # executor: << parameters.exec >>
    steps:
      # Start recording
      # - win-perf-diag/start-perflog
      # - win-perf-diag/record-wpr-in-background:
      #     for-sec: 100
      #     split-by-sec: 60
      - run:
          command: C:\Users\circleci.PACKER-648C8BAD\DiskSpd\amd64\diskspd.exe -d60 -W15 -C15 -c128M -t4 -o4 -b8k -L -r -Sh -w50 c:\disk-speed-test.dat
          name: Disk Speed
      # Stop recording and save records
      # - win-perf-diag/ensure-and-save-wpr
      # - win-perf-diag/stop-and-save-perflog

workflows:
  disk-speed:
    jobs:
      - gitclone-1
      - gitclone-2
      - gitclone-3