version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.2.1

parameters:
  browser:
    type: string
    default: ${DEFAULT_BROWSER}
  
executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/regression-qaa/

commands:
  install_local_browsers:
      description: Install Chrome and Firefox
      parameters:
        chrome_browser_version:
          type: string
          default: "latest"
      steps:
          - browser-tools/install-chrome:
              chrome-version: latest #<< parameters.chrome_browser_version >>

workflows:
  build_on_changes:
    jobs:
      - regression_build:
          name: Site Tour

jobs:
  regression_build:
    executor: docker_node
    parameters:
      chrome_browser_version:
        type: string
        default: ""

    steps:
      - install_local_browsers:
          chrome_browser_version: << parameters.chrome_browser_version >>