version: 2.1

orbs:
  # python: circleci/python@2.1.1
  mac: circleci/macos@2.3.4

jobs:
  build:
    macos:
      xcode: 14.3.1
    resource_class: macos.x86.medium.gen2
    steps:
      - run: xcrun simctl list
      - mac/preboot-simulator:
          version: '16.2'
          device: "iPhone 14 Pro Max"     
      - run: xcrun simctl list
      # - run:
      #     command: xcrun simctl bootstatus "${MACOS_ORB_DEVICE_UDID}"
      - mac/wait-until-simulator-booted # doesnt work on m1
workflows:
  workflow-mac:
    jobs:
      - build

