version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Current dir
          command: pwd


workflows:
  build_and_deploy:
    jobs:
      - approve:
          type: approval
          context: approval
      - build:
          requires: approve