version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
          
      - run:
          name: Set variable
          shell: powershell.exe
          environment:
            APP_VERSION: 1.2.3
          command: |
            $env:APP_VERSION
            setx APP_VERSION "5.4.91" /M
            refreshenv
            $env:APP_VERSION

      - run: 
          name: Set as context env var
          shell: powershell.exe
          command: |
            $env:CIRCLE_WORKFLOW_ID
            $env:APP_VERSION
            
            $uri = "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/{0}" -f $CIRCLE_WORKFLOW_ID
            $headers = @{
              "Circle-Token" = "$env:CIRCLE_TOKEN"
              "content-type" = "application/json"
            };
            $body = @{
              value = "$env:APP_VERSION"
            }

            Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

  print-var:
    executor:
      name: win/default
    steps:

        - run:
            name: Print var
            shell: powershell.exe
            environment:
              APP_VERSION: 1.2.3
            command: |
              $env:APP_VERSION
              setx APP_VERSION $env:APP_VERSION_CONTEXT
              $env:APP_VERSION
              refreshenv
              $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build:
          context: aea
      - print-var:
          context: aea
          requires:
            - build