version: 2.1

jobs:
  deploy_to_environment:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Testing env var not exist
          command: |
            circleci-agent step halt
            
      - run:
          name: env var
          command: |
            sleep 20
            echo $MYENVVAR

workflows:
  fusedocs-deploy-integ:
    jobs:
      - deploy_to_environment:
          name: fusedocs-deploy-integ