version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:12.13
    resource_class: medium

    steps:
      - checkout
      - run:
          name: npm check
          command: /home/circleci/.nvm/versions/node/v12.13.1/bin/npm
            
workflows:
  push:
    jobs:
      - test
