version: 2.1

orbs:
  mac: circleci/macos@2.0.0

jobs:
  permissions-check:

    macos:
      xcode: 13.1.0

    steps:

      - run:
          name: Granting Safari permissions and enabling safaridriver
          command: |
              if csrutil status | grep -q 'disabled'; then
                  epochdate=$(($(date +'%s * 1000 + %-N / 1000000')))
                  macos_major_version=$(sw_vers -productVersion | awk -F. '{ print $1 }')
                  if [[ $macos_major_version -le 10 ]]; then
                    defaults write com.apple.Safari AllowRemoteAutomation 1
                  else
                    tcc_service_accessibility="replace into access (service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,indirect_object_identifier,flags,last_modified) values (\"kTCCServiceAccessibility\",\"/usr/sbin/sshd\",1,2,4,1,0,\"UNUSED\",0,$epochdate);"
                    tcc_service_events="replace into access (service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,indirect_object_identifier,flags,last_modified) values (\"kTCCServiceAppleEvents\",\"/usr/sbin/sshd\",1,2,4,1,0,\"com.apple.systemevents\",0,$epochdate);"
                    sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_accessibility"
                    sudo sqlite3 "/Users/distiller/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_accessibility"
                    sudo sqlite3 "/Users/distiller/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_events"
                    sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_events"
                    osascript -e ./tmp.applescript
                  fi
                  sudo safaridriver --enable
              else
                  echo "Unable to add permissions! System Integrity Protection is enabled on this image"
                  echo "Please choose an image with SIP disabled. Documentation: https://circleci.com/docs/2.0/testing-macos"
                  exit 1
              fi

      - run:
          name: Create screencapture directory
          command: mkdir -p ~/artifacts/screencapture
      - run:
          name: Capture Screen
          command: screencapture -x ~/artifacts/screencapture/screenshot.png
      - run:
          name: Set Ruby Version
          command: sed -i '' 's/^chruby.*/chruby ruby-2.6/g' ~/.bash_profile

      - run:
          name: Check Ruby Version
          command: ruby -v

      - mac/switch-ruby:
          version: "3.0"

      - run:
          name: Check Ruby Version Again
          command: ruby -v

      - store_artifacts:
          path: ~/artifacts
      - mac/list-permissions
      - mac/list-permission-types
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
