version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1
  docker: circleci/docker@1.5.0

executor:
  docker/hadolint:
    tag: 2.4.0-debian

jobs:
  nodestuffs:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Python Stuff
          command: |
            pyenv versions

workflows:
  docker_test:
    jobs:
      - docker/hadolint
  welcome:
#     triggers:
#       - schedule:
#           cron: "47,50,53,56,59 * * * *"
    jobs:
      - nodestuffs
#       - welcome/run:
#           filters:
#             branches:
#               ignore:
#                 - testbranch
