version: 2.1

executors:
  docker_node:
    docker:
      - image: cimg/base:2021.07
    resource_class: medium

commands:
  install_cqlsh:
    description: Install cqlsh
    steps:
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python3-pip
      # - run:
      #     name: Make make make multi-threaded
      #     command: |
      #       sudo mv /usr/bin/make /usr/bin/make.bak
      #       sudo echo /usr/bin/make.bak --jobs=8 $@ > sudo /usr/bin/make
      #       sudo chmod 766 /usr/bin/make
      - run:
          name: Install cqlsh
          command: pip3 install cqlsh | while read line ; do echo "$(date +"%T") > $line" ; done ;

workflows:
  build_on_changes:
    jobs:
      - build:
          name: Site Tour

jobs:
  build:
    executor: docker_node

    steps:
      - restore_cache:
          keys:
            - my-cache
      
      - run:
          name: Get Ubuntu image
          command: |
            mkdir ./to_cache
            wget -P ./to_cache https://releases.ubuntu.com/16.04.7/ubuntu-16.04.6-desktop-i386.iso

      - install_cqlsh
      - save_cache:
          key: my-cache
          paths:
            - ./to_cache/
