version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large

    steps:
      - run:
          name: Set and retrieve vars
          command: |
            sudo mkdir /canton
            echo 'export "TEST1=CHANGED"' >> $BASH_ENV
            source $BASH_ENV
            echo $TEST1

      - run:
          name: Retreive var
          command: |
            pwd
            set | grep TEST1
            
      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test
