version: 2.1
  
jobs:
  cimg:
    docker:
      - image: cimg/ruby:2.7.5-node
    steps:
      - run: sudo apt install -y minimagick

      - run: dpkg -s minimagick
          
workflows:
  build-deploy:
    jobs:
      - cimg