version: 2.1

orbs:
  mac-permissions: circleci/macos@1.1.0

jobs:
  permissions-check:

    macos:
      xcode: 12.4.0

    steps:
      - run:
          name: Add VNC user
          command: sudo /usr/sbin/sysadminctl -addUser vncuser -fullName "VNC User" -password 'Password1' -admin
      - mac-permissions/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
      - mac-permissions/add-permission:
          bundle-id: "com.apple.sshd"
          permission-type: "KTCCServiceScreenCapture"
      - run:
          name: Create screencapture directory
          command: mkdir ~/screencapture
      - run:
          name: Capture Screen Recording
          command: screencapture -V2 ~/screencapture/capture.mov
          background: true
      - run:
          name: Capture Screen Recording (Terminal)
          command: /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal screencapture -V2 ~/screencapture/capture.mov
      - run:
          name: Capture Screenshot
          command: screencapture -x ~/screencapture/capture.png
      - mac-permissions/list-permissions
      - mac-permissions/list-permission-types
      - store_artifacts:
          path: ~/screencapture
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
