version: 2.1
setup: true


parameters:
  aws_account:
    description: "Context CircleCI value for the aws account. Example: aws-devops"
    type: string
    default: "master"

orbs:
  continuation: circleci/continuation@1.0.0


jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cimg/base:2022.03 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - continuation/continue:
          configuration_path: .circleci/continuation_config.yml
          parameters: |
            {
              "aws_account": "<< pipeline.parameters.aws_account >>"
            }

workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - << pipeline.parameters.aws_account >>