version: 2.1

jobs:
  deploy_to_environment:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Sleep and exit code 1
          command: |
            sleep 10
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/job/$CIRCLE_BUILD_NUM/cancel \
              -H "Circle-Token: $CIRCLE_TOKEN"
          background: true
            
      - run:
          name: apt update and upgrade
          command: |
            sudo apt update
            sudo apt full-upgrade -y

workflows:
  fusedocs-deploy-integ:
    jobs:
      - deploy_to_environment:
          name: fusedocs-deploy-integ
          context: orb-publishing