version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
    welcome:
      triggers:
        - schedule:
            cron: "47,50,53,56,59 * * * *"
      jobs:
        - welcome/run:
            filters:
              branches:
                ignore:
                  - testbranch
