# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  checkout_and_build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: xlarge
    steps:
      - run:
          name: Find current directory
          command: pwd

workflows:
  main_workflow:
    jobs:
      - checkout_and_build
