version: 2.1

orbs:
  # python: circleci/python@2.1.1
  mac: circleci/macos@2.3.4

jobs:
  build:
    parameters:
      device:
        type: string
        default: "iPhone 13 Pro Max"
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - run: xcrun simctl list
      - mac/preboot-simulator:
          version: '16.2'
          device: << parameters.device >>      
      - run: xcrun simctl list
      - run:
          command: xcrun simctl bootstatus "${MACOS_ORB_DEVICE_UDID}"
      - mac/wait-until-simulator-booted # doesnt work on m1
workflows:
  workflow-mac:
    jobs:
      - build