version: 2.1

jobs:
  build:
    parameters:
      version:
        default: "14.2.0"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run: nvm install 16.13
      - run: |
          nvm install 16.13
          nvm alias default 16.13
          echo 'nvm use default &>/dev/null' >> "$BASH_ENV"
workflows:
  workflow-mac:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["14.2.0"]