version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:

  ui-tests:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2021.10.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;arm64-v8a
          post-emulator-launch-assemble-command: ./gradlew assembleDemoDebugAndroidTest
          test-command: ./gradlew connectedDemoDebugAndroidTest


  # build:
  #   executor:
  #     name: android/android-machine
  #   steps:
  #     - checkout
  #     - flutter/install_sdk_and_pub:
  #         flutter_version: 2.2.3
  #     - flutter/install_android_gradle
  #     - android/create-avd:
  #         avd-name: myavd
  #         system-image: system-images;android-29;default;x86
  #         install: true
  #     - android/start-emulator:
  #         avd-name: myavd
  #         no-window: true
  #         restore-gradle-cache-prefix: v1a
  #     # - flutter/install_android_gem
  #     # - run:
  #     #     command: bundle exec fastlane distribute
  #     #     working_directory: ios

workflows:
  build-and-test:
    jobs:
      - ui-tests