version: 2.1

orbs:
  mac: circleci/macos@2.1.0
  browser: circleci/browser-tools@1.2.5

jobs:
  build:
    macos:
      xcode: 12.5.1
    resource_class: large
    steps:
      - browser/install-chrome:
          chrome-version: latest
      
workflow:
  build:
    jobs:
      - build