version: 2.1

parameters:
  pipelineSingleQuotes:
    type: string
    default: '1234567890'
  pipelineDoubleQuotes:
    type: string
    default: "1234567890"

jobs:
  local:
    docker:
      - image: circleci/node:latest

    parameters:
      elementSingleQuotes:
        type: string
        default: '1234567890'
      elementDoubleQuotes:
        type: string
        default: "1234567890"

    steps:
      - run:
          name: Pipeline Single Quotes!
          command: echo << pipeline.parameters.pipelineSingleQuotes >>
    steps:
      - run:
          name: Pipeline Double Quotes!
          command: echo << pipeline.parameters.pipelineDoubleQuotes >>
    steps:
      - run:
          name: Element Single Quotes!
          command: echo << parameters.elementSingleQuotes >>
    steps:
      - run:
          name: Element Double Quotes!
          command: echo << parameters.elementDoubleQuotes >>
             
workflows:
  version: 2
  build:
    jobs:
      - local
