version: 2.1

jobs:
  test:
    docker:
      - image: tesseractshadow/tesseract4re
    steps:
      - run:
          name: Install Ruby
          command: |
            apt update
            apt install -y ruby

workflows:
  test:
    # branch protection guarantees tests have already run on master;
    # we elect not to test staging or preproduction merges
    jobs:
      - test