# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build

jobs:
  checkout_and_build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - run:
          name: prep
          command: |
            sudo apt-get update
            sudo apt-get install cmake
            sudo apt-get install --fix-missing
            sudo apt-get install -y nodejs build-essential
            sudo apt-get install pkg-config
            bundle install --jobs=4 --retry=3 --path vendor/bundle