version: 2.1

jobs:
  deploy_to_environment:
    docker:
      - image: google/cloud-sdk:390.0.0
    steps:
      - checkout
      - run: which gsutil
      - run: gsutil --help

workflows:
  fusedocs-deploy-integ:
    jobs:
      - deploy_to_environment:
          name: fusedocs-deploy-integ