version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    parameters:
      sleep:
        type: integer
    steps:
      - run:
          name: Random fail
          command: |
            sleep << parameters.sleep >>
            exit $((RANDOM % 2))
            echo $?


workflows:
  build_and_deploy:
    jobs:
      - approval:
          type: approval
      - build:
          matrix:
            parameters:
              sleep: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          requires: approval