version: 2.1
# orbs:
#   jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    resource_class: small

    steps:
      - run:
          name: Multiline Test 1
          command: >
            echo foo
              bar
              baz
          when: always
      - run:
          name: Multiline Test 2
          command: >
            echo foo
            bar
            baz
          when: always
      - run:
          name: Multiline Test 3
          command: |
            echo foo \
            bar \
            baz
          when: always

workflows:
  main-workflow:
    jobs:
      - build 