version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:current
    resource_class: medium
    working_directory: ~

    steps:
      - node/install-packages

workflows:
  main-workflow:
    jobs:
      - build:
          context:
            - second
            - first

