version: 2.1

orbs:
  macos: circleci/macos@2.5.1


jobs:
  build:
    macos:
      xcode: "16.0.0"
    resource_class: macos.m1.medium.gen1
    steps:
      # - macos/enable-vnc
      - macos/install-rosetta
      - run:
          name: Install Android SDK
          command: pwd
      - macos/list-permission-types
      
            # # (yes || true) |
            # sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools" "emulator" "extras;google;m2repository" "extras;android;m2repository"
            # export AndroidSdkDirectory=$ANDROID_SDK_ROOT
      # - run:
      #     name: Install API levels
      #     command: |
      #       (yes || true) | sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools" "emulator" "extras;google;m2repository" "extras;android;m2repository"
      #       export AndroidSdkDirectory=$ANDROID_SDK_ROOT
      # - run:
      #     name: Check SDK levels
      #     command: sdkmanager --list
      # - run:
      #     security find-generic-password -a myaccount -s circleci.keychain
      # - gcp-cli/install
      # - run:
          # name: install gcp gcp-cli
          # command: |
          #   (New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe", "$env:Temp\GoogleCloudSDKInstaller.exe")
          #   & $env:Temp\GoogleCloudSDKInstaller.exe
          # shell: powershell.exe

      # - run:
      #     name: Check Ruby version
      #     command: which -a ruby && ruby --version

workflows:
  macos:
    jobs:
    
      - build