version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
          
      - run:
          name: Set variable
          shell: powershell.exe
          environment:
            APP_VERSION: 1.2.3
          command: |
            $env:APP_VERSION
            setx APP_VERSION "5.4.91" /M
            refreshenv
            $env:APP_VERSION

      - run: 
          name: Set as context env var
          shell: powershell.exe
          command: |
            $env:CIRCLE_WORKFLOW_ID
            $env:APP_VERSION
            refreshenv
            $uri = "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/APP_VERSION_$env:CIRCLE_SHA1"
            $headers = @{
              "Circle-Token" = "$env:CIRCLE_TOKEN"
              "content-type" = "application/json"
            };
            $body = @{
              value = "$env:APP_VERSION"
            }

            Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

            # echo $uri

            # $APP_VERSION_NAME = "APP_VERSION_$env:CIRCLE_SHA1"
            
            # echo $APP_VERSION_NAME

            # $APP_VERSION = (Get-Variable -name $APP_VERSION_NAME).Value

  print-var:
    executor:
      name: win/default
    steps:

      - run:
          name: Print var
          shell: powershell.exe
          environment:
            APP_VERSION: 1.2.3
          command: |
            # $env:CIRCLE_SHA1

            # ## This works to get the name of the variable.
            # $APP_VERSION_NAME = "APP_VERSION_$env:CIRCLE_SHA1"
            # echo $APP_VERSION_NAME

            # $APP_VERSION = (Get-Variable -name $APP_VERSION_NAME).Value

            $env:APP_VERSION_b921001fbfb2659aeca52dcc77a46b598a8da862

workflows:
  whatos:
    jobs:
      - build:
          context: aea
      - print-var:
          context: aea
          requires:
            - build