version: 2.1
# orbs:
#   jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
    resource_class: small

    steps:
      - run:
          name: Multiline Test 1
          command: echo order

workflows:
  main-workflow:
    jobs:
      - build:
          context:
            - second
            - first

