version: 2.1

jobs: 
  build:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    steps: 
      - run:
          name: Brew install
          command: brew install --cask android-commandlinetools
          # background: true
      - run: 
          name: Install sdkman
          command: ls -al ~/Library/Caches/Homebrew
          
workflows:
  build_and_deploy:
    jobs:
      - build