version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  # Name the workflow "welcome"
  cron:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - welcome/run
