version: 2.1

# orbs:
  # node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: cimg/postgres:15.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - run:
          name: curl localhost:5432
          command: sleep 5 && curl localhost:5432
      - run: psql postgres://postgres:password@localhost:5432/postgres

workflows:
  main-workflow:
    jobs:
      - build