version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: 
      name: win/server-2022
      shell: powershell.exe
    environment:
      - APP_VERSION: 'unchanged'
    steps:
      - checkout
      - run:
          shell: powershell.exe
          name: setx
          command: |
            $Env:svcFile = Get-Content -Path "$Env:CIRCLE_WORKING_DIRECTORY\testfile.txt"

            echo "svcFile is $Env:svcFile"
            echo "APP_VERSION is $Env:APP_VERSION"

            setx APP_VERSION %svcFile% /m

            echo "svcFile is $Env:svcFile"
            echo "APP_VERSION is $Env:APP_VERSION"


      - run:
          command: |
            Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' svcFile
            Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' APP_VERSION


workflows:
  version: 2
  build-deploy:
    jobs:
      - build