# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build
          context:
            - my-context

jobs:
  checkout_and_build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: context
          command: echo $demokey