version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

jobs: 
  build:
    docker:
      - image: cimg/base:current
        # auth:
        #   username: $DOCKERHUB_USER
        #   password: $DOCKERHUB_PASS
    resource_class: small
    steps:
      - run: 
          name: Present Working Directory
          command: pwd
      - snyk/install
          
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - dockerhub
