version: 2.1

orbs:
  mac: circleci/macos@2.3.0
  # mac: circleci/macos@dev:60b9d34b9bdfbc6c7eff90de81d70d7d059f31be
  # browser: circleci/browser-tools@1.4.0

jobs:

  build:
    macos:
      xcode: 14.2.0
      # resource_class: macos.x86.medium.gen2
    resource_class: macos.x86.medium.gen2

    steps:
      - run:
          name: Check Ruby

      - run:
          name: Set chruby
          command: sed -i '' 's/^chruby.*/chruby ruby-3.0/g' ~/.bash_profile

      - run:
          name: Check Ruby

      
workflows:
  build_and_test:
    jobs:
      - build