version: 2.1

jobs:
  build:
    parameters:
      version:
        default: "14.2.0"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          name: PWD
          command: pwd

workflows:
  workflow-mac:
    jobs:
      - build
      #     matrix:
      #       parameters:
      #         xcode_version: ["14.2.0"]