version: 2.1

jobs:
  test:
    docker:
      - image: tesseractshadow/tesseract4re
    steps:
      - run:
          name: Ruby  
          command: ruby -v

workflows:
  test:
    # branch protection guarantees tests have already run on master;
    # we elect not to test staging or preproduction merges
    jobs:
      - test