version: 2.1

jobs:
  build:
    docker:
      - image: circleci/postgres:alpine
    steps:
      - run:
          name: Set environment variable
          command: echo 'export TFPLAN="Does this work with text?"' >> $BASH_ENV
      - run:
          name: BASH_ENV
          command: source $BASH_ENV
      - run:
          name: Echo env var
          command: echo ${TFPLAN}

workflows:
  build-test:
    jobs:
      - build