version: 2.1

jobs:
  build:
    parameters:
      version:
        default: "14.2.0"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run: brew update
      - run: brew install node@16.13
      - run: brew switch node 16.13
workflows:
  workflow-mac:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["14.2.0", "14.3.0"]