version: 2.1

jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:202010-01
    steps:
      
      - run:
          name: Check Docker version
          command: docker --version



workflows:
  build:
    jobs:
      - build