version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Current working directory
          command: pwd

workflows:
  pre:
    jobs:
      - build
