version: 2.1
  
jobs:
  cimg:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - run: java -version

      - run: npm install -g appium

          
workflows:
  build-deploy:
    jobs:
      - cimg