version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15
    steps:
      - run:
          name: Steppy-step
          command: echo "This is a steppy-step" && sleep 60

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: my_build
          pre-steps:
            - run:
                name: Pre-step
                command: echo "This is a pre-step"
          post-steps:
            - run:
                name: Post-step
                command: echo "This is a post-step"