version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: stable

      steps:

        - run:
            name: Check dotnet versions
            command: dotnet --list-sdks

        - run:
            name: Install dotnet 4.8
            command: |
              mkdir c:\Temp
              Start-BitsTransfer -Source 'https://go.microsoft.com/fwlink/?linkid=2088631'  -Destination "C:\Temp\Net4.8.exe"; & "C:\Temp\Net4.8.exe" /q /norestart
            shell: powershell.exe

        - run:
             name: Check dotnet versions
             command: dotnet --list-sdks

workflows:
  version: 2
  build-deploy:
    jobs:
      - build