version: 2.1

orbs:
  mac: circleci/macos@2.0.1

jobs:
  build:
    macos:
      xcode: 12.5.0
    steps:
      - run:
          name: Check shell
          command: echo $SHELL

workflow:
  build:
    jobs:
      - build