version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.12
    resource_class: small

    steps:
      - run:
          name: top
          command: top
          background: true

workflows:
  build_and_deploy:
    jobs:
      - build:
          matrix:
            parameters:
              name: ["1", "2", "3"]