version: 2.1

orbs:
  node: 'circleci/node@4.7.0'
<<<<<<< HEAD
=======
  serverless: 'circleci/serverless-framework@1.0.1'
  slack: 'circleci/slack@3.4.2'
>>>>>>> 7a90568 (Testing SLS)

commands:
  deploy:
    description: 'Deploy to AWS'
<<<<<<< HEAD
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploying Core
          command: NODE_OPTIONS=--max_old_space_size=2048 pwd
      # - run:
      #     name: Deploying Campaign
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Journey
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Segment
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Integration
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Revenue
      #     command: sls deploy --stage << parameters.stage >>
=======
    parameters:
      stage:
        type: string
        default: 'dev'
    steps:
      - attach_workspace:
          at: .
      - serverless/setup
      - run:
          name: Deploying Core
          command: NODE_OPTIONS=--max_old_space_size=2048 sls deploy --verbose --stage << parameters.stage >>
      - run:
          name: Deploying Campaign
          command: sls deploy --stage << parameters.stage >>
      - run:
          name: Deploying Journey
          command: sls deploy --stage << parameters.stage >>
      - run:
          name: Deploying Segment
          command: sls deploy --stage << parameters.stage >>
      - run:
          name: Deploying Integration
          command: sls deploy --stage << parameters.stage >>
      - run:
          name: Deploying Revenue
          command: sls deploy --stage << parameters.stage >>
      - slack/status:
          success_message: ':tada: *$CIRCLE_PROJECT_REPONAME* deployed to *<< parameters.stage >>*'
          failure_message: ':red_circle: *$CIRCLE_PROJECT_REPONAME* deployment to *<< parameters.stage >>* has failed!'
>>>>>>> 7a90568 (Testing SLS)

jobs:

  deploy-dev:
<<<<<<< HEAD
    docker:
      - image: cimg/node:12.18
    steps:
      - deploy

workflows:

  build:
    jobs:
      - deploy-dev
=======
    executor: serverless/default
    steps:
      - deploy:
          stage: 'dev'

workflows:

  build:
    jobs:
      - deploy-dev:
>>>>>>> 7a90568 (Testing SLS)
