version: 2.1

orbs:
  macos: circleci/macos@2.4.1

jobs:
  build:
    macos:
      xcode: "14.2.0"
    steps:
      - run:
          name: current dir
          command: pwd
      - macos/enable-vnc:
          username: al
          password: $MAC_ORB_VNC_PASSWORD

workflows:
  build-and-test:
    jobs:
      - build