# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

workflows:
  main_workflow:
    jobs:
      - checkout_and_build:
          context:
            - my-context

jobs:
  checkout_and_build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          name: context
          command: echo $demokey
      - run:
          name: Get directory location
          command: pwd
      - run:
          name: Check /etc/apt/apt.conf
          command: cat /etc/apt/apt.conf