version: 2.1

parameters:
  browser:
    type: string
    default: ${DEFAULT_BROWSER}
  desktop:
    type: string
    default: "false"
  parallelism:
    description: "Number of containers to run in parallel"
    type: integer
    default: 10
  run_accessibility:
    type: boolean
    default: false
  run_deploy:
    type: boolean
    default: false
  run_manual_build:
    type: boolean
    default: false
  run_smokes:
    type: boolean
    default: false
  target_env:
    description: "Demo Environment to trigger the smoke tests against"
    type: string
    default: ${TARGET_ENV}
  test_path:
    description: "Path to test folder, or specific test file"
    type: string
    default: "\"./tests/**/*.js\""
  v2_petition_show:
    description: "Whether to test the v2 petition page"
    type: string
    default: "false"

orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.1.3

executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/regression-qaa/

commands:

  install_local_browsers:
      description: Install Chrome and Firefox
      parameters:
        chrome_browser_version:
          type: string
          default: "89.0.4389.90"
      steps:
          - browser-tools/install-firefox
          - browser-tools/install-chrome:
              chrome-version: << parameters.chrome_browser_version >>

workflows:
  build_on_changes:
    jobs:
      - regression_build:
          name: Site Tour
          parallelism: 1

jobs:
  regression_build:
    executor: docker_node
    parameters:
      browser:
        type: string
        default: << pipeline.parameters.browser >>
      chrome_browser_version:
        type: string
        default: ""
      parallelism:
        type: integer
        default: 10 # I've raised a bug with CircleCi, we're unable to use << pipeline.parameters.parallelism >> as the default value here
      desktop:
        type: string
        default: << pipeline.parameters.desktop >>
      path:
        type: string
        default: << pipeline.parameters.test_path >>
    parallelism: << parameters.parallelism >>

    steps:
      - install_local_browsers:
          chrome_browser_version: << parameters.chrome_browser_version >>