{
  "version": 2.1,
  "workflows": {
    "build_and_deploy": {
      "jobs": [
        {
          "hold": {
            "type": "approval",
            "matrix": {
              "parameters": {
                "minimum": [0],
                "exclusiveMaximum": [10]
              }
            }
          }
        }
      ]
    }
  }
}