version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.1

executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers

commands:
  install_local_browsers:
    description: Install Chrome and Firefox
    parameters:
      chrome_browser_version:
        type: string
        default: "latest"
    steps:
      - checkout
      - run:
          name: Check Chrome URL
          command: |
            while true; do
            sleep 10
            curl -I -sS https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /dev/null --fail
            done
            return 0
          background: true
      - run:
          name: Sleep
          command: sleep 60m

workflows:
  build_on_changes:
    jobs:
      - regression_build:
          name: Site Tour

jobs:
  regression_build:
    executor: docker_node

    steps:
      - install_local_browsers
          #chrome_browser_version: << parameters.chrome_browser_version >>