version: 2.1

orbs:
  win: circleci/windows@<< matrix.orb-version >>

jobs:
  build:
    executor:
      name: win/default
      
    steps:
      # - checkout
      - run: systeminfo
      - run:
          name: Check for NPM
          shell: powershell.exe
          command: npm --version


workflows:
  build-deploy:
    jobs:
      - build:
          name: build-<< matrix.version >>
          matrix:
            parameters:
              version: [ "1", "2", "3", "4", "5" ]
              orb-version: [ "2.4.0", "5.0.0" ]