version: 2.1

orbs:
  mac: circleci/macos@2.1.0

jobs:
  build:
    macos:
      xcode: 13.3.0
    resource_class: macos.x86.medium.gen2
    steps:
      - run:
          name: Install gradle
          command: brew install gradle
workflow:
  build:
    jobs:
      - build