version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.0.10
    steps:
      - checkout
      - run:
          name: Commandy command
          command: git diff --name-only origin/master...HEAD

workflows:
  test:
    # branch protection guarantees tests have already run on master;
    # we elect not to test staging or preproduction merges
    jobs:
      - test