version: '2.1'
# orbs:
#   android: circleci/android@1.0.3
jobs:
  test:
    machine:
    steps:
      - run:
          name: Dir
          command: pwd

workflows:
  Unit-Tests:
    jobs:
      - test