version: 2.1

executors:
  docker_node:
    docker:
      - image: circleci/golang:1
    resource_class: xlarge

commands:
  install_cqlsh:
    description: Install cqlsh
    steps:
      - run:
          name: Install pip
          command: |
            sudo apt install -y python3-pip
            sudo apt remove python
      - run:
          name: Make make make multi-threaded
          command: |
            sudo cp /usr/bin/make /usr/bin/make.bak
            make.bak --jobs=8 $@
      - run:
          name: Install cqlsh
          command: pip3 install --install-option="--jobs=8" cqlsh | while read line ; do echo "$(date +"%T") > $line" ; done ;

workflows:
  build_on_changes:
    jobs:
      - build:
          name: Site Tour

jobs:
  build:
    executor: docker_node

    steps:
      - install_cqlsh