version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      # - run:
      #     name: Check top
      #     command: top
      #     background: true
      - run:
          name: Profile CPU and memory every 5s (background)
          command: |
            # Generate a random number between 0 and 1
            RANDOM_NUM=$(( $RANDOM % 2 ))

            # Exit with either exit code 0 or 1, depending on the random number
            if [ $RANDOM_NUM -eq 0 ]; then
              exit 0
            else
              exit 1
            fi
              
          # background: true
      # - run:
      #     name: Sleep
      #     command: sleep 30


workflows:
  build_and_deploy:
    jobs:
      - build

# VS Code Extension Version: 1.2.0