version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.1

executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers

commands:
  install_local_browsers:
    description: Install Chrome and Firefox
    parameters:
      chrome_browser_version:
        type: string
        default: "latest"
    steps:
      - run:
          name: Install Chrome
          command: |
            cd /home/circleci && wget -O google-chrome-stable_current_amd64.deb -t 5 "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" \
            && (sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install)  \
            && rm -rf google-chrome-stable_current_amd64.deb \
            && sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' \
            "/opt/google/chrome/google-chrome" \
            && google-chrome --version
#      - browser-tools/install-chrome:
#          chrome-version: << parameters.chrome_browser_version >>

workflows:
  build_on_changes:
    jobs:
      - regression_build:
          name: Site Tour

jobs:
  regression_build:
    executor: docker_node

    steps:
      - install_local_browsers
          #chrome_browser_version: << parameters.chrome_browser_version >>