version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      
    steps:
      # - checkout
      - run:
          name: Install node with NVM
          command: nvm install 14.18.1 64 && nvm use 14.18.1 64
      - run:
          name: Check NPM version
          command: npm --version
      - run:
          name: Check Node version
          command: node --version


workflows:
  workflow:
    jobs:
      - build:
          name: Build << matrix.name >>
          matrix:
            parameters:
              name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]