version: 2.1

parameters:
  browser:
    type: string
    default: ${DEFAULT_BROWSER}

orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.1.3

executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/regression-qaa/

commands:
  install_local_browsers:
      description: Install Chrome and Firefox
      parameters:
        chrome_browser_version:
          type: string
          default: "89.0.4389.90"
      steps:
          - browser-tools/install-firefox
          - browser-tools/install-chrome:
              chrome-version: << parameters.chrome_browser_version >>

workflows:
  build_on_changes:
    jobs:
      - lint-only
      - regression_build:
          name: Activity Metric Service
          path: "\"./tests/user_activity_metrics/**/*.js\""
          parallelism: 1
          requires:
            - lint-only

jobs:
  lint-only:
    parallelism: 1
    executor: docker_node

    steps:
      - env_setup
      - run:
          name: Run lint checks
          command: npm run lint