version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    parameters:
      docker_name:
        type: string
    steps:
      - run:
          command: pwd

  deploy:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          command: pwd

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build 1
          matrix:
            parameters:
              docker_name: ["one", "two", "three"]
      - build:
          name: build 2
          matrix:
            parameters:
              docker_name: ["one", "two", "three"]
      - deploy:
          name: deploy
          # matrix:
          #   parameters:
          #     docker_name: ["one", "two", "three"]
          requires:
            - build