version: 2.1

jobs:

  test:
    docker:
      - image: cimg/android:2022.04.1-node
    resource_class: medium

    steps:
      - checkout
      - run:
          name: Check gcloud
          command: gcloud --version
            
workflows:
  push:
    jobs:
      - test
