version: 2.1

jobs: 
  build:
    docker:
      - image: lokalise/lokalise-cli-2:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    resource_class: small
    steps:
      - run: 
          name: Present Working Directory
          command: pwd
          
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - dockerhub
