version: 2.1

# orbs:
#   win: circleci/windows@2.4.0

executors:
  win_med:
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium

jobs:
  build:
    # executor:
    #   name: win/default
    #   shell: bash.exe
    #   size: medium
    executor: win_med

    steps:
      # - checkout
      - run:
          name: Install node with NVM
          command: |
            # Check if Node 14.18.1 is installed
            if ! command -v node &> /dev/null || [[ $(node -v) != "v14.18.1" ]]; then
                echo "Node 14.18.1 is not installed"
                # Install Node 14.18.1 with NVM
                nvm install 14.18.1 64 && nvm use 14.18.1 64
                # Loop until Node 14.18.1 is installed
                while ! command -v node &> /dev/null || [[ $(node -v) != "v14.18.1" ]]; do
                    echo "Waiting for Node 14.18.1 to be installed..."
                    sleep 1
                done
                echo "Node 14.18.1 is now installed"
            else
                echo "Node 14.18.1 is already installed"
            fi


      - run:
          name: Check NPM version
          command: npm --version
      - run:
          name: Check Node version
          command: node --version


workflows:
  workflow:
    jobs:
      - build:
          name: Build
          #  << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]