version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    paramters:
      version:
        type: integer
    steps:
      - run:
          name: Current dir
          command: |
            return %((RANDOM % 2))
            echo $?


workflows:
  build_and_deploy:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]