version: 2.1

orbs:
  windows: circleci/windows@5.0.0


jobs:
  build:
    executor: 
      name: windows/server-2019
    steps:
      - run:
          name: set env var
          command: |
            $Env:PATH -split ";" | Set-Content -Path C:\Temp\job1-1.txt
            $Env:PATH += ";C:\Program Files\LLVM\bin"
            $Env:PATH -split ";" | Set-Content -Path C:\Temp\job1-2.txt

      - run:
          name: recall env var
          command: |
            $Env:PATH -split ";" | Set-Content -Path C:\Temp\job2.txt

      - run:
          name: set env var again
          command: |
            $Env:PATH += ";C:\Program Files\LLVM\bin"
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv
            $Env:PATH split ";" | Set-Content -Path C:\Temp\job3.txt

      - run:
          name: recall env var
          command: |
            $Env:PATH -split ";" | Set-Content -Path C:\Temp\job4.txt

      - store_artifacts:
          path: C:\Temp

workflows:
  check-this-out:
    jobs:
      - build