version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

jobs:
  build:
    docker:
      - image: cimg/android:2021.10.1-ndk
    steps:
      - run:
          name: download bundletool
          command: |
            curl https://github.com/google/bundletool/releases/download/1.10.0/bundletool-all-1.10.0.jar --output ~/bundletool.jar
            chmod +x ~/bundletool.jar
      - run:
          name: run bundletool
          command: java -jar ~/bundletool version

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build