version: 2.1

jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:2022.04.2
    steps:
      
      - run:
          name: Check Docker version
          command: docker --version

      # - run:
      #     name: Check OpenSSL Version
      #     command: openssl version


workflows:
  build:
    jobs:
      - build