version: 2.1


jobs: 
  build:
    docker:
      - image: cimg/base:current
        # auth:
        #   username: $DOCKERHUB_USER
        #   password: $DOCKERHUB_PASS
    resource_class: small
    # parameters:
    #   my-condition:
    #     type: env_var_name
    #     default: MY_CONDITION
    steps:
      - when:
          condition: << parameter.my-condition >>
          steps:
            - run: 
                name: "True"
                command: echo "This is true"
                # background: true
      # - snyk/install

  # test:
  #   docker:
  #     - image: cimg/base:current
  #   resource_class: small
  #   steps:
  #     - run: pwd
          
workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              version: ["0.1", "0.2", "0.3"]
      #     context:
      #       - dockerhub
      # - test
  # build_and_deploy_webhook:
  #   when:
  #     equal: [ webhook, << pipeline.trigger_source >> ]
  #   jobs:
  #     - build:
  #         context:
  #           - dockerhub
  #     - test