version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:latest
    steps:
      - run:
          name: Current dir
          command: echo $CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  build-and-test:
    jobs:
      - build