version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    resource_class: small


    steps:
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Create script
          command: touch script.sh && echo "echo \"Hello world!\"" >> script.sh
          background: false
      - run:
          name: Set executable for file, not exec for directory
          command: |
            chmod 755 script.sh
            chmod 744 .
      - run:

          name: Check top
          command: top
          background: true
      - run:
          name: Sleep
          command: sleep 300

workflows:
  build_and_deploy:
    jobs:
      - build:

          name: my_build

