version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          name: Set var
          command: VERSION=123
      - run:
          name: retreive var and export var
          command: |
            echo $VERSION
            export VERSION=321
      - run:
          name: retrieve exported var
          command: echo $VERSION


workflows:
  build_and_deploy:
    jobs:
      - build