version: 2.1

orbs:
  mac-permissions: circleci/macos@1.1.0

jobs:
  permissions-check:

    macos:
      xcode: 12.5.1

    steps:
      - mac-permissions/add-permission:
          bundle-id: "com.apple.Terminal"
          permission-type: "kTCCServiceScreenCapture"
      - run:
          name: Create screencapture directory
          command: mkdir ~/screencapture
      - run:
          name: Capture Screenshot
          command: screencapture -x ~/screencapture/capture.png
      - run:
          name: Capture Screen Recording
          command: |
            echo "screencapture -V30 ~/screencapture/wow_so_hacky.mov" > ~/screencapture/tmp.sh
            chmod 755 ~/screencapture/tmp.sh
            open -a Terminal ~/screencapture/tmp.sh
      - run:
          name: Pause for 40 seconds
          command: sleep 40
      - store_artifacts:
          path: ~/screencapture
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
