version: 2.1

orbs:
  mac-permissions: circleci/macos@1.1.0

parameters:
  pipelineSingleQuotes:
    type: string
    default: '1234567890'
  pipelineDoubleQuotes:
    type: string
    default: "1234567890"

jobs:
  permissions-check:

    macos:
      xcode: 12.5.0

    steps:
      - mac-permissions/add-permission:
          bundle-id: "com.apple.sshd"
          permission-type: "kTCCServiceScreenCapture"
      - run:
          name: Create screencapture directory
          command: mkdir ~/screencapture
      - run:
          name: Capture Screen Recording
          command: screencapture -V2 ~/screencapture/capture.mov
          background: true
      - run:
          name: Capture Screenshot
          command: screencapture -x ~/screencapture/capture.png
      - mac-permissions/list-permissions
      - mac-permissions/list-permission-types
      - store_artifacts:
          path: ~/screencapture
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
