version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:13.0
    resource_class: medium

    steps:
      - run:
          name: xvfb
          command: which Xvfb
          # background: true
      # - run:
      #     name: Profile CPU and memory every 5s (background)
      #     command: |
      #       while true; do
      #         sleep 5
      #         printf "\n\n$(date)\n"
      #         top -b -c -n 1
      #         echo "======"
      #       done
      #     background: true
      # - run:
      #     name: Sleep
      #     command: sleep 30


workflows:
  build_and_deploy:
    jobs:
      - build
      # :
      #     matrix:
      #       parameters:
      #         name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50"]

# VS Code Extension Version: 1.4.0