version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: 
      name: win/server-2022
      shell: powershell.exe
    environment:
      - APP_VERSION: 'unchanged'
    steps:
      - run:
          shell: powershell.exe
          name: setx
          command: |
            echo "svcFile is $Env:svcFile"
            echo "APP_VERSION is $Env:APP_VERSION"
            $APP_VERSION = $svcFile
            refreshenv
            echo "svcFile is $Env:svcFile"
            echo "APP_VERSION is $Env:APP_VERSION"
            # Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' svcFile
            # Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' APP_VERSION


      # - run: |
      #     echo $Env:svcFile
      #     echo $Env:APP_VERSION


workflows:
  version: 2
  build-deploy:
    jobs:
      - build