version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2019-cuda:current'
      resource_class: windows.gpu.nvidia.medium
      shell: powershell.exe -ExecutionPolicy Bypass
      
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker pull public.ecr.aws/docker/library/hello-world:nanoserver-ltsc2022
            docker run public.ecr.aws/docker/library/hello-world:nanoserver-ltsc2022


workflows:
  version: 2
  build-deploy:
    jobs:
      - build