version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2-node
    resource_class: small

    steps:
      - run:
          name: top
          command: rvm remove 3.2.2 && rvm install 3.2.2 --with-openssl-dir=$HOME/.rvm/usr
          background: false

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build # << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3"]