version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202008-01
      resource_class: large
    working_directory: /canton

    steps:
      - run:
          name: Currect dir
          command: pwd

      - run:
          name: create dir
          command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test
