version: 2.1

jobs:
  python:
    parameters:
      python-version:
        type: string
    docker:
      - image: ubuntu:22.04
    steps:
      - run:
          name: install python << parameters.python-version >>
          command: |
            apt -y update
            # echo "Installing spc"
            # apt -y install software-properties-common
            # echo "Added deadsnakes"
            # add-apt-repository ppa:deadsnakes/ppa
            echo "Installing Python"
            apt -y install python<< parameters.python-version >>

workflows:
  test:
    jobs:
      - python:
          matrix:
            parameters:
              python-version: ["3.8","3.9","3.10"]