version: 2.1

orbs:
  slack: 'circleci/slack@3.4.2'

jobs:
  build:
    - image: circleci/postgres:alpine
    steps:
      - run:
          name: Set environment variable
          command: export "TFPLAN=`terraform show tfplan | tail -1`" >> $BASH_ENV
      - run:
          name: BASH_ENV
          command: source $BASH_ENV
      - run:
          name: Echo env var
          command: echo $TFPLAN

workflows:
  build-test:
    jobs:
      - build
