version: 2.1

jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2204:2022.04.1
    steps:

      - run:
          name: Check OpenSSL Version
          command: openssl version
      
      - run:
          name: 'Install Project Node'
          command: |
            set +x
            source ~/.bashrc

            nvm install 12
            NODE_DIR=$(dirname $(which node))
            echo "export PATH=$NODE_DIR:\$PATH" >> $BASH_ENV

      - run:
          name: Check OpenSSL Version
          command: openssl version

workflows:
  build:
    jobs:
      - build