version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
      
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: Check VS version
          shell: powershell.exe
          command: devenv /ver
      - run:
          name: Check MSBuild version
          shell: powershell.exe
          command: msbuild /ver

workflows:
  version: 2
  build-deploy:
    jobs:
      - build