version: 2.1

orbs:
  macos: circleci/macos@2.4.1


jobs:
  build:
    macos:
      xcode: "15.2.0"
    resource_class: macos.m1.medium.gen1
    steps:
      # - macos/enable-vnc
      - macos/install-rosetta
      - run:
          name: Install Android SDK
          command: |
            brew update
            brew install --cask temurin@8
            brew install --cask android-sdk
            export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
            echo $JAVA_HOME
            export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
            export ANDROID_SDK_PATH=/opt/homebrew/Caskroom/android-sdk
            export ANDROID_HOME=/opt/homebrew/Caskroom/android-sdk
            export ANDROID_SDK_ROOT=/opt/homebrew/Caskroom/android-sdk
            # # (yes || true) |
            # sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools" "emulator" "extras;google;m2repository" "extras;android;m2repository"
            # export AndroidSdkDirectory=$ANDROID_SDK_ROOT
      - run:
          name: Install API levels
          command: |
            (yes || true) | sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools" "emulator" "extras;google;m2repository" "extras;android;m2repository"
            export AndroidSdkDirectory=$ANDROID_SDK_ROOT
      - run:
          name: Check SDK levels
          command: sdkmanager --list
      # - run:
      #     security find-generic-password -a myaccount -s circleci.keychain
      # - gcp-cli/install
      # - run:
          # name: install gcp gcp-cli
          # command: |
          #   (New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe", "$env:Temp\GoogleCloudSDKInstaller.exe")
          #   & $env:Temp\GoogleCloudSDKInstaller.exe
          # shell: powershell.exe

      - run:
          name: Check Ruby version
          command: which -a ruby && ruby --version

workflows:
  macos:
    jobs:
    
      - build:
          pre-steps:
            - run: rbenv global 3.2.2