version: 2.1

jobs: 
  build:
    docker:
      - image: cimg/node:19.6.0
    resource_class: medium
    steps: 
      - run: 
          name: xvfb
          command: |
            curl -s get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
          
workflows:
  build_and_deploy:
    jobs:
      - build