version: 2.1

setup: true

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

jobs:
  my_job:
    docker:
      - image: cimg/base:2023.12-22.04
    steps:
      - git-shallow-clone/checkout:
          depth: 1

workflows:
  setup:
    jobs:
      - my_job

# version: 2.1

# jobs:
#   passing:
#     docker:
#       - image: cimg/base:2023.12-22.04
#     steps:
#       - run:
#           name: Something
#           command: pwd
#       - run:
#           name: Check status
#           command: echo ${CIRCLE_JOB}

#   failing:
#     docker:
#       - image: cimg/base:2023.12-22.04
#     steps:
#       - run:
#           name: Something
#           command: pwd
#       - run:
#           name: Check status
#           command: echo ${CIRCLE_JOB}
#       - run:
#           name: Fails
#           command: skdjfhdjhfg

# workflows:
#   build-deloy:
#     jobs:
#       - passing:
#           post-steps:
#             - run:
#                 name: Check status
#                 command: echo ${CIRCLE_JOB}
#                 when: always
#       - failing:
#           post-steps:
#             - run:
#                 name: Check status
#                 command: echo ${CIRCLE_JOB}
#                 when: always
          
      

# version: 2.1

# orbs:
#   # jira: circleci/jira@2.0.1

# commands:
#   when_step:
#     parameters:
#       when:
#         type: enum
#         enum: ["on_success","on_fail","always"]
#         default: on_success
#     steps:
#       - run:
#           when: << parameters.when >>
#           name: Present directory
#           command: pwd
      

# jobs:
#   build:
#     docker:
#       - image: cimg/base:2022.06
#     working_directory: ~/mystuff
    
#     steps:
#       - setup_remote_docker:
#           docker_layer_caching: false
#           # version: default
#       # - run: docker --version
#       - checkout
#       # - run:
#       #     name: fail step
#       #     command: asdasdsadf
#       - when_step:
#           when: on_success
#       - run:
#           name: Build stuff
#           command: echo "Building stuff!"
#       # - jira/notify

#   test:
#     docker:
#       - image: cimg/base:2022.06
#     steps:
#       - checkout
#       - run:
#           name: Test stuff
#           command: echo "Testing stuff!"

#   deploy:
#     docker:
#       - image: cimg/base:2022.06
#     steps:
#       - checkout
#       - run:
#           name: Deploy stuff
#           command: echo "Deploying stuff!"

# workflows:
#   buid-test-deploy:
#     jobs:
#       - build:
#           context: jira
#       - test:
#           requires:
#             - build
#       # - approve:
#       #     type: approval
#       #     requires:
#       #       - test
#       # - deploy:
#       #     requires:
#       #       - approve
#       #     filters:
#       #       branches:
#       #         only:
#       #           - master
