version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
      
    steps:
      # - checkout
      - run:
          name: Check Docker version
          command: docker --version

workflows:
  workflow:
    jobs:
      - build:
          name: Build
          #  << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]