version: 2.1
# orbs:
#   jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/node:current
    resource_class: medium

    steps:
      - run:
          name: install stuff
          command: npm ci --verbose

workflows:
  main-workflow:
    jobs:
      - build:
          context:
            - second
            - first

