version: 2

jobs:
  local:
    macos:
      xcode: "11.3.0"
    steps:
      - run:
          name: Brew gubbins
          command: |
                brew unlink python@2
                brew update-reset
                brew tap wix/brew
                brew install applesimutils
                brew install watchman
             
workflows:
  version: 2
  build:
    jobs:
      - local
