version: '2.1'
# orbs:
#   android: circleci/android@1.0.3
jobs:
  test:
    docker:
      - image: cimg/go:1.17.6
    steps:
      - checkout
      - run:
          name: Testing apps
          no_output_timeout: 30s
          command: |
            cd apps
            chmod +x *
            TERM=xterm-256color
      - run: ./apps/aloha
      - run: ./apps/ksleep 2 1.5
      - run: ./apps/ksshgen -a rsa --override -b 4096
      - run: ./apps/kpwdgen -l 16 -s 0 -c 1
      - run:
          name: Script with all apps
          command: |
            source ~/.profile
            TERM=xterm-256color
            PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
            PS2='> '
            PS4='+ '
            set -o xtrace
            echo $TERM
            echo $SHELL
            env
            set
            cd apps
            sh ./run.sh
  
workflows:
  Unit-Tests:
    jobs:
      - test