version: 2.1

jobs: 
  build:
    docker:
      - image: cimg/base:current
        # auth:
        #   username: $DOCKERHUB_USER
        #   password: $DOCKERHUB_PASS
    resource_class: small
    steps:
      - run: 
          name: traceroute
          command: |
            sudo apt update
            sudo apt install traceroute
            traceroute www.google.com
          background: true
      - run:
          name: sleep
          command: sleep 30
      # - snyk/install

  # test:
  #   docker:
  #     - image: cimg/base:current
  #   resource_class: small
  #   steps:
  #     - run: pwd
          
workflows:
  build_and_deploy_api:
    # when:
    #   equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - build
      #     context:
      #       - dockerhub
      # - test
  # build_and_deploy_webhook:
  #   when:
  #     equal: [ webhook, << pipeline.trigger_source >> ]
  #   jobs:
  #     - build:
  #         context:
  #           - dockerhub
  #     - test