version: 2.1

jobs:
  build:
    docker:
      - image: circleci/redis:5.0-alpine
    resource_class: large

    steps:

      - run:
          name: Get jar from maven repeatedly until forever
          command: pwd

      # - run:
      #     name: Set environment variable 1
      #     command: echo 'export TFPLAN1=$(pwd)' >> $BASH_ENV
      # - run:
      #     name: Echo env var 1
      #     command: echo $TFPLAN1
      # - run:
      #     name: Set environment variable 2
      #     command: echo 'export TFPLAN2=`pwd`' >> $BASH_ENV
      # - run:
      #     name: Echo env var 2
      #     command: echo $TFPLAN2

workflows:
  build-test:
    jobs:
      - build:
          context: my-context