version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-node
    resource_class: medium

    steps:

      - run:
          name: Get current dir
          command: pwd
      
      - run:
          name: Check Node version
          command: node -v

      # - run:
      #     name: Set environment variable 1
      #     command: echo 'export TFPLAN1=$(pwd)' >> $BASH_ENV
      # - run:
      #     name: Echo env var 1
      #     command: echo $TFPLAN1
      # - run:
      #     name: Set environment variable 2
      #     command: echo 'export TFPLAN2=`pwd`' >> $BASH_ENV
      # - run:
      #     name: Echo env var 2
      #     command: echo $TFPLAN2

workflows:
  build-test:
    jobs:
      - build:
          context: my-context