version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    working_directory: ~/project/mystuff
    steps:
      - checkout
      - run:
          name: Build stuff
          command: echo "Building stuff!"

  test:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Test stuff
          command: echo "Testing stuff!"

  deploy:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Deploy stuff
          command: echo "Deploying stuff!"

workflows:
  buid-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approve
          filters:
            branches:
              only:
                - master
