version: 2.1

orbs:
  win: circleci/windows@<< parameters.orb-version >>

jobs:
  build:
    executor:
      name: win/default
      
    steps:
      # - checkout
      - run: systeminfo
      - run:
          name: Check for NPM
          shell: powershell.exe
          command: npm --version


workflows:
  build-deploy:
    jobs:
      - build:
          matrix:
            parameters:
              orb-version: [ "2.4.0", "5.0.0" ]
