version: 2.1

parameters:
  run_workflow:
    type: boolean
    default: true
  run-setup:
    type: boolean
    default: true

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    resource_class: medium

    steps:
      # - setup_remote_docker
      - run:
          name: PWD in remote docker
          command: ssh remote-docker "pwd"

# workflows:
#   build_and_deploy:
#     jobs:
#       - build
          # type: approval
          # matrix:
          #   parameters:
          #     1-array: [0,1]
          #     2-array: [0,1]
          #     3-array: [0,1]
          #     4-array: [0,1]

workflows:
  workflow:
    # when:
    #   and:
    #     - equal: [true, << pipeline.parameters.run-setup >>]
    #     - equal: [true, << pipeline.parameters.run_workflow >>]
    jobs:
      - build