version: 2.1

jobs: 
  build:
    docker:
      - image: cimg/base:2022.10
    resource_class: medium
    steps: 
      - run: 
          name: Install sdkman
          command: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
          
workflows:
  build_and_deploy:
    jobs:
      - build