version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      
    steps:
      # - checkout
      - run: systeminfo
      - run:
          name: Check for NPM
          shell: powershell.exe
          command: npm --version


workflows:
  workflow:
    jobs:
      - build:
          name: Build << matrix.name >>
          matrix:
            parameters:
              name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]