version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.4.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
      version: stable

    steps:
      # Commands are run in a Windows virtual machine environment
      - run:
          name: Download InstallerProjects VSIX
          command: curl -o "https://visualstudioclient.gallerycdn.vsassets.io/extensions/visualstudioclient/microsoftvisualstudio2017installerprojects/1.0.0/1620063166533/InstallerProjects.vsix"