version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:

  ui-tests:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.06.2
    steps:
      # - checkout
      # - android/start-emulator-and-run-tests:
      #     system-image: system-images;android-32;google_apis;x86_64
      #     # post-emulator-launch-assemble-command: ./gradlew assembleDemoDebugAndroidTest
          # test-command: ./gradlew connectedDemoDebugAndroidTest
      - android/create-avd:
          avd-name: android_12
          install: true
          system-image: system-images;android-32;google_apis;x86_64
      - android/start-emulator:
          avd-name: android_12
          camera-back: emulated
          camera-front: emulated
          post-emulator-launch-assemble-command: ''
          wait-for-emulator: false
          no-window: false
          additional-args: -skin 415x830
      - run:
          name: wait for emulator startup
          command: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done;'
      - run:
          name: Sleep
          command: sleep 600

  # build:
  #   executor:
  #     name: android/android-machine
  #   steps:
  #     - checkout
  #     - flutter/install_sdk_and_pub:
  #         flutter_version: 2.2.3
  #     - flutter/install_android_gradle
  #     - android/create-avd:
  #         avd-name: myavd
  #         system-image: system-images;android-29;default;x86
  #         install: true
  #     - android/start-emulator:
  #         avd-name: myavd
  #         no-window: true
  #         restore-gradle-cache-prefix: v1a
  #     # - flutter/install_android_gem
  #     # - run:
  #     #     command: bundle exec fastlane distribute
  #     #     working_directory: ios

workflows:
  build-and-test:
    jobs:
      - ui-tests