version: 2.1
  
jobs:
  cimg:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - run: nvm ls
      - store_test_results:
          path: ~/project/bazel-testlogs

workflows:
  build-deploy:
    jobs:
      - cimg