version: 2.1

commands:
  when_step:
    parameters:
      when:
        type: enum
        enum: ["on_success","on_fail","always"]
        default: on_success
    steps:
      - run:
          when: << parameters.when >>
          name: Present directory
          command: pwd
      

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    working_directory: ~/mystuff
    steps:
      - checkout
      - run:
          name: fail step
          command: asdasdsadf
      - when_step:
          when: always
      - run:
          name: Build stuff
          command: echo "Building stuff!"

  test:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Test stuff
          command: echo "Testing stuff!"

  deploy:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - run:
          name: Deploy stuff
          command: echo "Deploying stuff!"

workflows:
  buid-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approve
          filters:
            branches:
              only:
                - master
