# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  main_workflow:
    jobs:
      - checkout_and_build:
          context:
            - my-context

jobs:
  checkout_and_build:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - browser-tools/install-chrome:
          chrome-version: "latest"
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install