version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0

jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.2.3
      - flutter/install_android_gradle
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-29;default;x86
          install: true
      # - flutter/install_android_gem
      # - run:
      #     command: bundle exec fastlane distribute
      #     working_directory: ios

workflows:
  build-and-test:
    jobs:
      - build