version: 2.1

jobs:
  rm_rvm:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.large
    steps:
      - run: sudo rm -rf /opt/circleci/.rvm
      - run: sudo mkdir -p /mnt/ramdisk

  keep_rvm:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.large
    steps:
      - run: sudo mkdir -p /mnt/ramdisk

  implode_rvm:
    machine:
      image: ubuntu-2204:current
      resource_class: arm-large
    steps:
      - run: rvm implode --force
      - run: sudo mkdir -p /mnt/ramdisk


workflows:
  build:
    jobs:
      - rm_rvm
      - keep_rvm
      - implode_rvm