version: 2.1

orbs:
  mac: circleci/macos@2.0.1

jobs:
  build:
    macos:
      xcode: 11.7.0
    steps:
      - run:
          name: Check drive space
          command: df -hl

workflow:
  build:
    jobs:
      - build