# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  checkout_and_build:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - run:
          name: Find current directory
          command: pwd
  install_local_browsers:
    description: Install Chrome and Firefox
    parameters:
      chrome_browser_version:
        type: string
        default: "89.0.4389.90"
    steps:
      - browser-tools/install-firefox
      - browser-tools/install-chrome:
          chrome-version: << parameters.chrome_browser_version >>

workflows:
  main_workflow:
    jobs:
      - checkout_and_build
