version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: stable

      steps:

        - run:
            name: Check python version
            command: python --version

        - run:
            name: Switch Python version
            command: py -3.9
            shell: powershell.exe

        - run:
             name: Check python versions
             command: python --version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build