{
    "version": 2.1,
    "jobs": {
      "build": {
        "docker": [
          {
            "image": "cimg/node:18.13.0-browsers"
          }
        ],
        "resource_class": "small",
        "steps": [
          {
            "run": {
              "name": "xvfb",
              "command": "which Xvfb"
            }
          }
        ]
      }
    },
    "workflows": {
      "build_and_deploy": {
        "jobs": [
          "build"
        ]
      }
    }
  }