version: 2.1

orbs:
  mac: circleci/macos@2.1.0
  browser: circleci/browser-tools@1.2.5

jobs:
  build:
    macos:
      xcode: 10.0.1337
    # resource_class: macos.x86.medium.gen2
    steps:
      - browser/install-chrome:
          chrome-version: latest
      
workflow:
  build:
    jobs:
      - build