version: 2.1

jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-2004:2022.07.2
    steps:
      
      - run:
          name: Check Docker version
          command: docker --version

workflows:
  build:
    jobs:
      - build