version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - run:
          name: Current dir
          command: pwd

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
          filters:
            tags:
              only: /^v.*/
