version: 2.1

orbs:
  mac-permissions: circleci/macos@1.1.0

parameters:
  pipelineSingleQuotes:
    type: string
    default: '1234567890'
  pipelineDoubleQuotes:
    type: string
    default: "1234567890"

jobs:
  permissions-check:

    macos:
      xcode: 12.5.0

    steps:
      - run:
          name: Pipeline Single Quotes!
          command: echo << pipeline.parameters.pipelineSingleQuotes >>
      - mac-permissions/list-permissions
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
