version: 2.1

orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@5.0

jobs:
  build:
    parameters:
      node-version:
        type: string
    executor: 
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          shell: powershell.exe
          name: setx
          command: npm install --legacy-peer-deps --verbose


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          matrix:
            parameters:
              node-version: ["14.18.0", "14.18.2", "14.19.2", "14.20.1", "15.14.0", "16.17.1", "17.9.1", "18.9.1"]