version: 2.1

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: large

    steps:
      - run:
          name: Set and retrieve vars
          command: |
            # echo $TEST1
            # # export TEST1=CHANGED
            # # echo $TEST1
            # # export TEST1
            # echo 'export TEST1="CHANGED"' >> "$BASH_ENV"
            # echo $TEST1

            sudo mkdir /canton
            echo "export CIRCLE_WORKING_DIRECTORY=/canton" >> $BASH_ENV

      - run:
          name: Retreive var
          command: echo $TEST1
            
      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build:
    jobs:
      - build_and_test
