version: 2.1

jobs:

  build:
    docker:
      - image: cimg/node:18.4.0
    parameters:
      docker_name:
        type: string
    steps:
      - run:
          name: Current dir
          command: pwd

  deploy:
    docker:
      - image: cimg/node:18.4.0
    parameters:
      docker_name:
        type: string
    steps:
      - run:
          name: Current dir
          command: pwd

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build-v<< matrix.docker_name >>
          matrix:
            parameters:
              docker_name: ["one", "two", "three"]
      - deploy:
          name: deploy-v<< matrix.docker_name >>
          matrix:
            parameters:
              docker_name: ["one", "two", "three"]
          requires:
            - build-v<< matrix.docker_name >>