version: 2.1

orbs:
  windows: circleci/windows@5.0.0


jobs:
  build:
    executor: 
      name: windows/server-2019
    steps:
      - run:
          name: set env var
          command: |
            Env:PATH -split ";"
            Env:PATH += ";C:\Program Files\LLVM\bin"
            Env:PATH split ";"

      - run:
          name: recall env var
          command: |
            Env:PATH -split ";"

      - run:
          name: set env var again
          command: |
            Env:PATH += ";C:\Program Files\LLVM\bin"
            Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
            refreshenv
            Env:PATH split ";"

      - run:
          name: recall env var
          command: |
            Env:PATH -split ";"

workflows:
  check-this-out:
    jobs:
      - build