version: 2.1

orbs:
  mac-permissions: circleci/macos@2.0.0

jobs:
  permissions-check:

    macos:
      xcode: 12.5.1

    steps:
      - mac-permissions/add-permission:
          bundle-id: "com.apple.sshd"
          permission-type: "kTCCServiceScreenCapture"
      - run:
          name: Create screencapture directory
          command: mkdir ~/screencapture          
      - run:
          name: Capture Screen
          command: screencapture -x ~//screencapture/screenshot.png
      - store_artifacts:
          path: ~/screencapture
      # - mac-permissions/list-permissions
      # - mac-permissions/list-permission-types
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
