version: 2.1

orbs:
  mac: circleci/macos@dev:20758105bf04a1fb756a623352dcfdca1c27ec81
  browser: circleci/browser-tools@1.2.5

jobs:
  build:
    macos:
      xcode: 12.5.1
      resource_class: macos.x86.medium.gen2
    steps:
      - run:
          name: Update homebrew
          command: brew update && brew upgrade
      # - mac/enable-vnc
      # - browser/install-chrome:
      #     chrome-version: latest
      
workflow:
  build:
    jobs:
      - build