version: 2.1

orbs:
  mac-permissions: circleci/macos@2.0.0

jobs:
  permissions-check:

    macos:
      xcode: 12.5.1

    steps:
      - mac-permissions/add-permission:
          bundle-id: "com.apple.sshd"
          permission-type: "kTCCServiceScreenCapture"
      - run:
          name: Capture Screen
          command: screencapture -x ~/silentscreenshot.jpg
      # - mac-permissions/list-permissions
      # - mac-permissions/list-permission-types
             
workflows:
  version: 2
  build:
    jobs:
      - permissions-check
