version: 2.1

jobs:
  build:
    docker:
      - image: circleci/postgres:alpine
    steps:
      - run:
          name: Set environment variable
          command: echo 'export TFPLAN-1="`pwd`"' >> $BASH_ENV
      - run:
          name: Echo env var
          command: echo $TFPLAN-1

workflows:
  build-test:
    jobs:
      - build