version: 2.1

orbs:
  mac: circleci/macos@2.3.0
  # mac: circleci/macos@dev:60b9d34b9bdfbc6c7eff90de81d70d7d059f31be
  browser: circleci/browser-tools@1.2.5

jobs:

  build:
    macos:
      xcode: 13.4.0
      # resource_class: macos.x86.medium.gen2
      resource_class: medium

    steps:
      run:
        name: GH API test
        command: curl https://api.github.com/zen
      # - mac/add-safari-permissions
      # - mac/enable-vnc
      # - mac/list-permissions
      # - mac/add-permission:
      #     bundle-id: "com.apple.Terminal"
      #     permission-type: "kTCCServiceMicrophone"
      # - mac/list-permissions
      # - mac/enable-vnc
      # - browser/install-chrome:
      #     chrome-version: latest
      
workflow:
  build:
    jobs:
      - build