version: 2.1

orbs:
  node: 'circleci/node@4.7.0'

commands:
  deploy:
    description: 'Deploy to AWS'
    parameters:
      stage:
        type: string
        default: 'dev'
    steps:
      - attach_workspace:
          at: .
      - serverless/setup
      - run:
          name: Deploying Core
          command: NODE_OPTIONS=--max_old_space_size=2048 pwd
      # - run:
      #     name: Deploying Campaign
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Journey
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Segment
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Integration
      #     command: sls deploy --stage << parameters.stage >>
      # - run:
      #     name: Deploying Revenue
      #     command: sls deploy --stage << parameters.stage >>

jobs:

  deploy-dev:
    executor: serverless/default
    steps:
      - deploy

workflows:

  build:
    jobs:
      - deploy-dev