version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:12.13
    resource_class: medium

    steps:
      - checkout
      - run:
          name: setup bazel
          command: /usr/lib/node_modules/npm --version
            
workflows:
  push:
    jobs:
      - test
