version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/server-2022
        version: edge

      steps:

        - run:
            name: Check .NET versions
            command: |
              dotnet --list-sdks
            shell: powershell.exe

workflows:
  version: 2
  build-deploy:
    jobs:
      - build