version: 2.1

orbs:
  mac: circleci/macos@2.3.0
  # mac: circleci/macos@dev:60b9d34b9bdfbc6c7eff90de81d70d7d059f31be
  # browser: circleci/browser-tools@1.4.0

jobs:

  build:
    macos:
      xcode: 13.4.0
      # resource_class: macos.x86.medium.gen2
    resource_class: macos.x86.medium.gen2

    parameters:
      attempt:
        type: string

    steps:
      - run:
          name: Download AgoraRtcEngine_iOS
          command: /usr/bin/curl -f -L -o /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/d20220914-4948-o0h3q9/file.zip https://download.agora.io/sdk/release/AgoraRtcEngine_iOS-3.7.0.3.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.2'
      
      # - browser/install-chrome:
      #     chrome-version: "103.0.5060.134"
      # - mac/add-safari-permissions
      # - mac/enable-vnc
      # - mac/list-permissions
      # - mac/add-permission:
      #     bundle-id: "com.apple.Terminal"
      #     permission-type: "kTCCServiceMicrophone"
      # - mac/list-permissions
      # - mac/enable-vnc
      # - browser/install-chrome:
      #     chrome-version: latest
      
workflow:
  build:
    jobs:
      - build:
          name: build-<< matrix.attempt >>
          matrix:
            parameters:
              attempt: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]