version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.07
    resource_class: small


    steps:
      # - setup_remote_docker:
      #     version: 20.10.23
      #     docker_layer_caching: true
      - run:
          name: Create script
          command: touch script.sh && echo "print('Hello from Python!')" >> script.sh
          background: false
      - run:
          name: Set executable for file, not exec for directory
          command: |
            chmod 755 script.sh
            chmod 744 .
      - run:
          name: Current dir
          command: |
            pwd
            ls -al
      - run:
          name: Run script
          command: ./script.sh
      - run:
          name: fix perm and run
          command: |
            chmod 755 .
            ./script.sh
          shell: python

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build # << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3"]