version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/base:2022.06
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

workflows:
  version: 2
  pre:
    jobs:
      - build
