version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: Testing npm
          command: npm --version

workflows:
  whatos:
    jobs:
      - build