version: 2.1

jobs: 
  build:
    macos:
      xcode: 14.2.0
    resource_class: medium
    steps: 
      - run:
          name: Background Disk Space
          command: |
            while true; do
              sleep 5
              df -h
              printf "\n===========\n"
            done
          background: true
      - run: 
          name: Install sdkman
          command: |
            sleep 20
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
          
workflows:
  build_and_deploy:
    jobs:
      - build