version: 2

jobs:
  local:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Print version on local docker
          command: hostnamectl
  remote:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Print version on remote docker
          command: |
            ssh remote-docker
            hostnamectl            
             
workflows:
  version: 2
  build:
    jobs:
      - build
      - remote
