version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.1

jobs:
  build:
    docker:
      - image: cimg/node:18.8.0-browsers
    steps:
      - run:
          name: Set var
          command: |
            VERSION="123"
            echo $VERSION
      - run:
          name: retreive var and export var
          command: |
            echo $VERSION
            echo 'export VERSION="321"' >> "$BASH_ENV"
      - run:
          name: retrieve exported var
          command: echo $VERSION

workflows:
  build_and_deploy:
    jobs:
      - shellcheck/check:
          name: my_check
      - build:
          name: my_build
          requires:
            - my_check
