version: 2.1

jobs:
  python:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run:
          name: Fail Fast
          when: always
          command: |
            if [[ $CIRCLE_BRANCH =~ "master" ]]; then
              echo "Not fast canceling - this is a major branch";
            else
              echo "Canceling workflow as a step resulted in failure"
              # curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}"
            fi;

workflows:
  test:
    jobs:
      - python