version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: 
      name: win/server-2022
      shell: powershell.exe
    environment:
      - APP_VERSION: 3.2.1
    steps:
      - run:
          shell: powershell.exe
          name: setx
          command: |
            setx APP_VERSION $env:svcFile /m
            refreshenv
            echo $Env:svcFile
            echo $Env:APP_VERSION
            $PSVersionTable

      - run: |
          echo $Env:svcFile
          echo $Env:APP_VERSION


workflows:
  version: 2
  build-deploy:
    jobs:
      - build