version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:12.13.0
    resource_class: medium

    steps:
      - checkout
      - run:
          name: npm check
          command: npm --version
            
workflows:
  push:
    jobs:
      - test
