version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
          
      # - run:
      #     name: Set variable
      #     shell: powershell.exe
      #     environment:
      #       APP_VERSION: 1.2.3
      #     command: |
      #       $env:APP_VERSION
      #       setx APP_VERSION "5.4.91" /M
      #       refreshenv
      #       $env:APP_VERSION

      - run: 
          name: Set as context env var
          shell: powershell.exe
          command: |
            # $uri = "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/APP_VERSION_$env:CIRCLE_WORKFLOW_ID"

            # echo $uri


            # echo "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/APP_VERSION_$env:CIRCLE_WORKFLOW_ID" | Out-File .\api_url.txt

            # type .\api_url.txt

            $env:CIRCLE_WORKFLOW_ID
            $env:APP_VERSION
            setx wfid $env:CIRCLE_WORKFLOW_ID /M
            refreshenv
            # $env:wfid
            Write-Output $env:wfid
            $uri = "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/APP_VERSION_$env:CIRCLE_SHA1"
            $headers = @{
              "Circle-Token" = "$env:CIRCLE_TOKEN"
              "content-type" = "application/json"
            };
            $body = @{
              value = "$env:APP_VERSION"
            }

            Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

            echo $uri

  print-var:
    executor:
      name: win/default
    steps:

        - run:
            name: Print var
            shell: powershell.exe
            environment:
              APP_VERSION: 1.2.3
            command: |
              $env:CIRCLE_SHA1

              $sha1 = $env:CIRCLE_SHA1
              setx APP_VERSION_NAME 'APP_VERSION_'$sha1 /M

              $env:APP_VERSION_NAME

              setx APP_VERSION APP_VERSION_NAME

              $env:APP_VERSION


              # $env:APP_VERSION_$env:CIRCLEC_SHA1

              # $env:APP_VERSION_NEW = "$env:APP_VERSION_$env:CIRCLE_SHA1"
              # $env:APP_VERSION_NEW
              
              # $env:APP_VERSION_$env:CIRCLE_SHA

              # $env:APP_VERSION
              # setx APP_VERSION $env:APP_VERSION_$env:CIRCLE_SHA1
              # $env:APP_VERSION
              # refreshenv
              # $env:APP_VERSION

workflows:
  whatos:
    jobs:
      - build:
          context: aea
      - print-var:
          context: aea
          requires:
            - build