version: 2.1

parameters:
  run_workflow:
    type: boolean
    default: true
  run-setup:
    type: boolean
    default: true

jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    resource_class: small

    steps:
      # - setup_remote_docker
      - checkout
      - run:
          name: PWD
          command: pwd
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/base:2023.06
    resource_class: small

    steps:
      - attach_workspace:
          at: .
      - run: pwd

# workflows:
#   build_and_deploy:
#     jobs:
#       - build
          # type: approval
          # matrix:
          #   parameters:
          #     1-array: [0,1]
          #     2-array: [0,1]
          #     3-array: [0,1]
          #     4-array: [0,1]

workflows:
  workflow:
    # when:
    #   and:
    #     - equal: [true, << pipeline.parameters.run-setup >>]
    #     - equal: [true, << pipeline.parameters.run_workflow >>]
    jobs:
      - build
      - test:
          requires:
            - build