version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    resource_class: small

    steps:
      - run:
          name: Create script
          command: touch script.sh && echo "echo \"Hello world!\"" >> script.sh
          background: false
      - run:
          name: Set executable for file, not exec for directory
          command: |
            chmod 755 script.sh
            chmod 744 .
      - run:
          name: Current dir
          command: |
            pwd
            ls -al
      - run:
          name: Run script
          command: ./script.sh
      - run:
          name: fix perm and run
          command: |
            chmod 755 .
            ./script.sh

workflows:
  build_and_deploy:
    jobs:
      - build:
          name: build # << matrix.name >>
          # matrix:
          #   parameters:
          #     name: ["1", "2", "3"]