version: 2.1

orbs:
    mac-permissions: circleci/macos@1.1.0

jobs:
  build-test:
    macos:
      xcode: 12.5.0
    steps:
        - mac-permissions/list-permission-types

workflow:
  build-and-test:
    jobs:
      - build-test