version: 2.1

jobs:

  test:
    machine: 
      image: ubuntu-2004:202111-02
    resource_class: medium

    steps:
      - checkout
      - run:
          name: setup bazel
          command: |
            wget https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64
            sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
            sudo chmod +x /usr/local/bin/bazel
            bazel version
            
      - restore_cache:
          key: bazel-cache-{{ .Branch }}
      - run:
          name: Run tests
          command:  |
            bazel test ...

      - store_test_results:
          path: bazel-testlogs/

      - save_cache:
          key: bazel-cache-{{ .Branch }}
          paths:
            - ~/.cache/bazel

workflows:
  push:
    jobs:
      - test
