version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.20
    steps:
      - run:
          name: Check top
          command: vmstat
          background: true
      - run:
          name: Sleep
          command: sleep 30


workflows:
  build_and_deploy:
    jobs:
      - build

# VS Code Extension Version: 1.2.0