version: 2.1

orbs:
    win: circleci/windows@2.2.0

jobs:
    build:
      executor: 
        name: win/default
        version: edge

      steps:

        - run:
            name: Check python version
            command: |
              py -3.9
              python --version
            shell: powershell.exe

workflows:
  version: 2
  build-deploy:
    jobs:
      - build