version: 2.1

parameters:
  #machine used for sonar scan job
  build-machine:
    type: string
    default: 'ubuntu-2204:current'
  workspace:
    type: string
    default: /tmp/workspace

orbs:
  security: cvs-digital/security@2

jobs:
  metadata-validation:
    machine:
      image: << pipeline.parameters.build-machine >>
    working_directory: << pipeline.parameters.workspace >>
    environment:
      GITHUB_ACTION: yes
    steps:
      - checkout
      - security/create-labels:
          workspace: << pipeline.parameters.workspace >>

workflows:
  stuff:
    jobs:
      - metadata-validation