version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

workflows:
  workflow:
    jobs:
      - node/test:
          version: '16.10.0-browsers'
          pkg-manager: npm
          setup:
            - browser-tools/install-chrome
