version: 2.1

executors:
  android-executor:
    machine:
      image: ubuntu-2004:202107-02
    # working_directory: ~/gelato-os-flutter

jobs:
  # rm_rvm:
  #   machine:
  #     image: ubuntu-2204:current
  #     resource_class: arm.large
  #   steps:
  #     - run: sudo rm -rf /opt/circleci/.rvm
  #     - run: sudo mkdir -p /mnt/ramdisk

  build:
    executor: android-executor
    steps:
      - run: 
          name: Check docker version
          command: docker --version

workflows:
  build_and_deploy:
    jobs:
      # - rm_rvm
      - build
      # - deploy:
      #     requires:
      #       - build
      # - implode_rvm