version: 2.1
  
jobs:
  build:
    machine: 
      image: ubuntu-2004:202111-02
    resource_class: medium
    
    steps:
      - checkout
      - run:
          name: Schema generator
          command: |
            chmod +x bazel-bin/glossary/schema-exporter/binary
            ./bazel-bin/glossary/schema-exporter/binary
      - store_test_results:
          path: ~/project/bazel-testlogs

workflows:
  build-deploy:
    jobs:
      - build