version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    shell: powershell.exe
    resource_class: alanjclark/windows-new-runner
    steps:
      - run: echo "Hi I'm in Runners!"
