version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
          
      - run:
          name: Set variable
          shell: powershell.exe
          parameters:
            parallelism_qty:
              type: string
              default: 1.2.3
          command: |
            $env:APP_VERSION
            setx APP_VERSION "5.4.90" /M
            refreshenv
            $env:APP_VERSION

      - run: 
          name: Set as context env var
          shell: powershell.exe
          command: |
            $uri = "https://circleci.com/api/v2/context/3186eab8-d7f9-4018-b326-37559f0f6bc6/environment-variable/APP_VERSION_CONTEXT"
            $headers = @{
              "Circle-Token" = "$env:CIRCLE_TOKEN"
              "content-type" = "application/json"
            };
            $body = @{
              value = "$APP_VERSION"
            }

            Invoke-RestMethod -Method Put -Uri $uri -Headers $headers -Body ($body| ConvertTo-Json) -ContentType 'application/json'

            # $env:APP_VERSION
            refreshenv
            $env:APP_VERSION_CONTEXT
        
      - run:
          name: Retrieve context
          shell: powershell.exe
          command: $env:APP_VERSION_CONTEXT

  print-var:
    executor:
      name: win/default
    steps:

        - run:
            name: Print var
            shell: powershell.exe
            command: |
              $env:APP_VERSION
              setx APP_VERSION $APP_VERSION_CONTEXT /M
              $env:APP_VERSION_CONTEXT
              refreshenv
              $env:APP_VERSION_CONTEXT

workflows:
  whatos:
    jobs:
      - build:
          context: aea
      - print-var:
          context: aea
          requires:
            - build