version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.2.1

parameters:
  browser:
    type: string
    default: ${DEFAULT_BROWSER}
  target_env:
    description: "Demo Environment to trigger the smoke tests against"
    type: string
    default: ${TARGET_ENV}
  test_path:
    description: "Path to test folder, or specific test file"
    type: string
    default: "\"./tests/**/*.js\""
  
executors:
  docker_node:
    docker:
      - image: cimg/node:current-browsers
    working_directory: ~/regression-qaa/

commands:
  install_local_browsers:
      description: Install Chrome and Firefox
      parameters:
        chrome_browser_version:
          type: string
          default: "latest"
      steps:
          - browser-tools/install-chrome:
              chrome-version: latest #<< parameters.chrome_browser_version >>

workflows:
  build_on_changes:
    jobs:
      - regression_build:
          name: Site Tour

jobs:
  regression_build:
    executor: docker_node
    parameters:
      chrome_browser_version:
        type: string
        default: ""
      desktop:
        type: string
        default: << pipeline.parameters.desktop >>
      path:
        type: string
        default: << pipeline.parameters.test_path >>

    steps:
      - install_local_browsers:
          chrome_browser_version: << parameters.chrome_browser_version >>