version: 2.1

jobs:
  build:
    parameters:
      version:
        default: "14.2.0"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run:
          name: Set env var
          command: |
            echo "Xcode Version was " $XCODE_VERSION
            XCODE_VERSION="14.1.0"
            echo 'export $XCODE_VERSION' >> $BASH_ENV
            echo "Xcode version is now " $XCODE_VERSION

      - run:
          name: Check xcode
          command: |
            echo "Xcode version is still " $XCODE_VERSION

workflows:
  workflow-mac:
    jobs:
      - build
      #     matrix:
      #       parameters:
      #         xcode_version: ["14.2.0"]