version: 2.1

jobs:
  build: # name of your job
    machine:
      image: ubuntu-2004:2022.10.1
      # docker_layer_caching: true
    resource_class: medium
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run:
            name: Hello World
            # shell: powershell.exe
            command: java -version

workflows:
  build-deploy:
    jobs:
      - build


# version: 2.1

# jobs:
#   my-job:
#     machine:
#       image: windows-server-2019-cuda:current
#     resource_class: windows.medium
    
#     steps:
#       - checkout
#       - run: which scp
#       - run: which ssh
#       # - run: scp --version
#       - run: ssh -V
#       - run: export DEBIAN_FRONTEND=noninteractive && sudo apt update && sudo apt-get install -y -o Dpkg::Options::="--force-confnew" --only-upgrade openssh-client openssh-server
#       - run: ssh -V


# workflows:
#   workflow:
#     jobs:
#       - my-job

# version: 2.1

# jobs:
#   build:
#     machine:
#       image: ubuntu-2204:2022.10.2
      
#     steps:
#       # - checkout
#       # - run:
#       #     name: Check Docker version
#       #     command: docker --version
#       - run:
#           name: Install stuff
#           command: |
#             # $nrconf{restart} = 'i';
#             sudo sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
#             sudo apt update && sudo apt install -y build-essential cmake clang clang-format esbuild shellcheck ninja-build hugo doxygen rapidjson-dev googletest libjavascriptcoregtk-4.0-dev
  
#   # unittest:
#   #   machine:
#   #     image: ubuntu-2004:202111-02
#   #     # docker_layer_caching: true
#   #   # working_directory: ~/hotpie

#   #   steps:
#   #     - run:
#   #         name: Install stuff
#   #         command: |
#   #           # $nrconf{restart} = 'i';
#   #           sudo apt update && sudo apt install -y build-essential cmake clang clang-format esbuild shellcheck ninja-build hugo doxygen rapidjson-dev googletest libjavascriptcoregtk-4.0-dev
#   #     # - checkout

# workflows:
#   workflow:
#     jobs:
#       - build:
#           name: Build
#       # - unittest
#           #  << matrix.name >>
#           # matrix:
#           #   parameters:
#           #     name: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]