version: 2.1

parameters:
  tag:
    default: '3.8'
    description: The `cimg/python` Docker image version tag.
    type: string
  use-redis:
    default: false
    description: Sidecar Redis container if required
    type: boolean


executors:
  base:
    parameters:
    docker:
      - image: cimg/python:<< pipeline.parameters.tag >>

jobs:
  build:
    executor: base
    steps:
      - run: echo hello
      - run: <<#pipeline.parameters.use-redis>>- image: redis:latest<</pipeline.parameters.use-redis>>