version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.20
    steps:
      - run:
          name: node version
          command: node --version
      - run:
          name: npm version
          command: npm --version


workflows:
  build_and_deploy:
    jobs:
      - build:
          name: my_build
          filters:
            branches:
              only:
                - dev
                - /releases\/.*/

# VS Code Extension Version: 1.2.0