version: 2.1

jobs:

  build:
    docker:
      - image: circleci/ruby:2.7.3
    resource_class: medium

    steps:
      - run:
          name: Get current dir
          command: pwd


  # - run:
  #     name: Get current dir
  #     command: |
  #       sudo apt-get update
  #       sudo apt-get -y install net-tools

  # - run:
  #     name: Poll netstat for debugging LY-1536
  #     command: |
  #       while true; do
  #         sudo netstat -atupn
  #         sleep 1
  #       done
  #     background: true

  # - run:
  #     name: Save env vars to file
  #     command: |
  #       echo $MYPASS >> ~/myenvvarpass.txt
  #       echo $MYCONTEXTPASS >> ~/mycontextpass.txt
  #       echo $MYNEWCONTEXTPASS >> ~/mynewcontextpass.txt
      
  #     - store_artifacts:
  #         path: ~/myenvvarpass.txt
          
  #     - store_artifacts:
  #         path: ~/mycontextpass.txt

  #     - store_artifacts:
  #         path: ~/mynewcontextpass.txt

      # - run:
      #     name: Set environment variable 1
      #     command: echo 'export TFPLAN1=$(pwd)' >> $BASH_ENV
      # - run:
      #     name: Echo env var 1
      #     command: echo $TFPLAN1
      # - run:
      #     name: Set environment variable 2
      #     command: echo 'export TFPLAN2=`pwd`' >> $BASH_ENV
      # - run:
      #     name: Echo env var 2
      #     command: echo $TFPLAN2

workflows:
  build-test:
    jobs:
      - build