version: 2.1

jobs:
  test:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - run:
          name: Commandy command
          command: |
            nvidia-smi
      - run:
          name: NVCC
          command: nvcc

workflows:
  test:
    # branch protection guarantees tests have already run on master;
    # we elect not to test staging or preproduction merges
    jobs:
      - test