version: 2.1

parameters:
  workflow_name:
    type: string
    default: "first_workflow"

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

    # working_directory: /canton

    steps:
      - run:
          name: Present working directory
          command: pwd

    # steps:
    #   - run:
    #       name: Set and retrieve vars
    #       command: |
    #         sudo mkdir /canton
    #         # echo 'export "CIRCLE_WORKING_DIRECTORY=/canton"' >> $BASH_ENV
    #         # echo 'export "CIRCLE_BUILD_NUM=123"' >> $BASH_ENV
    #         # source $BASH_ENV
    #         echo $CIRCLE_WORKING_DIRECTORY
            
    #   - run:
    #       name: Retreive var
    #       working_directory: /canton
    #       command: |
    #         echo $CIRCLE_WORKING_DIRECTORY
    #         pwd
            
      # - run:
      #     name: create dir
      #     command: sudo mkdir /canton

workflows:
  build<< pipeline.parameters.workflow_name >>:
    jobs:
      - build_and_test