version: 2.1

executors:
  android-executor:
    machine:
      image: android:2022.12.1
    working_directory: ~/gelato-os-flutter

jobs:
  # rm_rvm:
  #   machine:
  #     image: ubuntu-2204:current
  #     resource_class: arm.large
  #   steps:
  #     - run: sudo rm -rf /opt/circleci/.rvm
  #     - run: sudo mkdir -p /mnt/ramdisk

  build:
    executor: android-executor
    # machine:
    #   image: ubuntu-2204:current
    # resource_class: medium
    steps:
      # - run: 
      #     name: Gradle pwd
      #     command: |
      #       pwd
            # ./gradlew

      - run: 
          name: Create a file
          command: |
            touch file.txt
            echo "this is some text" >> ./file.txt

      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: android-executor
    steps:
      - attach_workspace:
          at: ~/gelato-os-flutter
      - run:
          name: List
          command: ls -al
  # implode_rvm:
  #   machine:
  #     image: ubuntu-2204:current
  #   resource_class: medium
  #   steps:
  #     - run: rvm implode --force
  #     - run: sudo mkdir -p /mnt/ramdisk


workflows:
  build_and_deploy:
    jobs:
      # - rm_rvm
      - build
      - deploy:
          requires:
            - build
      # - implode_rvm