version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run coverage
          command: coverage

workflows:
  test:
    # branch protection guarantees tests have already run on master;
    # we elect not to test staging or preproduction merges
    jobs:
      - test