version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.1
  node: circleci/node@4.0.0

# orbs:
#   aws-ecr: circleci/aws-ecr@7.3.0
#   aws-cli: circleci/aws-cli@2.0.6

installpip3: &installpip3
  name: install pip3
  command: |
    curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
    python3 get-pip.py

jobs:
  build:
    docker:
      - image: cimg/python:3.8.12-browsers
    steps:

      - node/install:
          install-npm: false
          install-yarn: true
          node-version: 12.22.6

      - run:
          name: Check Pip
          command: pip3 --version

      - run:
          name: install pip3
          command: |
            curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
            python3 get-pip.py

      - run:
          name: Check Pip
          command: pip3 --version

      - run:
          name: update PATH
          command: export PATH="$PATH:/home/circleci/.local/bin"

      - run:
          name: Check Pip
          command: pip3 --version

      # - run:
      #     name: Check location of Pip
      #     command: find -name "pip3"
      # - run:
      #     name: Check Pip
      #     command:  pip3 --version
      # - run:
      #     name: Install fresh pip3
      #     command: |
      #       curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
      #       python3 get-pip.py
      # - run:
      #     name: Check Pip
      #     command: pip3 --version
      # - run:
      #     name: Check location of Pip
      #     command: find -name "pip3"
      # - run:
      #     name: Set path for Pip
      #     command: export PATH="$PATH:/home/circleci/.local/bin"
      # - run:
      #     name: Check Pip again
      #     command: pip3 --version


    # machine:
    #   image: ubuntu-2004:202111-01
    # steps:
    #   - aws-cli/setup:
    #       override-installed: yes
    #       # version: '2.4.3'
    #   - aws-ecr/build-and-push-image:
    #       # account-url: AWS_ECR_ACCOUNT_URL
    #       # aws-access-key-id: AWS_ACCESS_KEY_ID
    #       # aws-secret-access-key: AWS_SECRET_ACCESS_KEY
    #       profile-name: ""
    #       repo: al-test

workflows:
  build-test:
    jobs:
      - build