version: 2.1

jobs:
  deploy_to_environment:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Testing env var not exist
          command: |
            sleep 30
            exit 1
          background: true
            
      - run:
          name: env var
          command: |
            sudo apt update
            sudo apt full-upgrade -y

workflows:
  fusedocs-deploy-integ:
    jobs:
      - deploy_to_environment:
          name: fusedocs-deploy-integ