version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: 
      name: win/default
    environment:
      - APP_VERSION: 3.2.1
    steps:
      - run: |
          setx APP_VERSION svcFile /m
          refreshenv
          echo $svcFile
          echo $Env:APP_VERSION


workflows:
  version: 2
  build-deploy:
    jobs:
      - build