version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  welcome:
    triggers:
      - schedule:
          cron: "7 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - welcome/run
